# Generated by Django 4.1.6 on 2023-06-06 10:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_delete_credential'),
    ]

    operations = [
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('key', models.CharField(blank=True, max_length=200, verbose_name='Key')),
                ('client_id', models.TextField(blank=True, verbose_name='Client ID')),
                ('client_secret', models.TextField(blank=True, verbose_name='Client secret')),
                ('api_key', models.TextField(blank=True, verbose_name='API key')),
                ('extra', models.JSONField(default=dict, verbose_name='Extra data')),
            ],
            options={
                'verbose_name': 'Platform',
                'verbose_name_plural': 'Platforms',
            },
        ),
        migrations.CreateModel(
            name='Credential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('credentials', models.JSONField(blank=True, default=dict, verbose_name='Credentials')),
                ('token', models.TextField(blank=True, verbose_name='Token')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Company')),
                ('platform', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='integration.platform', verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'Credential',
                'verbose_name_plural': 'Credentials',
            },
        ),
    ]
