# Generated by Django 4.1.6 on 2023-06-06 20:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0016_remove_category_menu_category_menu'),
        ('integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='logo',
            field=models.URLField(blank=True, max_length=255, verbose_name='Logo'),
        ),
        migrations.CreateModel(
            name='PlatformMenuItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Name')),
                ('base_price', models.FloatField(blank=True, verbose_name='Base price')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.menuitem', verbose_name='Menu Item')),
                ('platform', models.ManyToManyField(blank=True, to='integration.platform', verbose_name='Platform')),
            ],
            options={
                'verbose_name': 'Platform Menu Item',
                'verbose_name_plural': 'Platform Menu Items',
            },
        ),
    ]
