# Generated by Django 4.1.6 on 2023-11-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0003_alter_platform_client_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='api_key',
        ),
        migrations.AddField(
            model_name='platform',
            name='token',
            field=models.TextField(blank=True, verbose_name='API token'),
        ),
    ]
