# Generated by Django 4.1.6 on 2023-11-13 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0004_remove_platform_api_key_platform_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='platform',
            name='key',
        ),
        migrations.AlterField(
            model_name='platform',
            name='extra',
            field=models.JSONField(blank=True, verbose_name='Extra data'),
        ),
    ]
