# Generated by Django 4.1.6 on 2023-11-13 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0054_modifiergroup_otter_id'),
        ('integration', '0005_remove_platform_key_alter_platform_extra'),
    ]

    operations = [
        migrations.CreateModel(
            name='Onboarding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('pending', 'pending'), ('active', 'active')], max_length=25)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='integration.platform', verbose_name='Platform')),
                ('onboarding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
