# Generated by Django 4.1.6 on 2023-11-14 12:47

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0006_onboarding'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='store_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Client secret'),
        ),
    ]
