# Generated by Django 4.1.6 on 2023-11-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0007_onboarding_store_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='platform',
            name='mode',
            field=models.CharField(choices=[('test', 'test'), ('production', 'production')], default='test', max_length=200, verbose_name='Mode'),
        ),
    ]
