# Generated by Django 4.1.6 on 2023-11-24 17:53

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
        ('integration', '0008_platform_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='onboarding',
            name='locations',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='food.location', verbose_name='locations'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='store_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='store key'),
        ),
    ]
