# Generated by Django 4.1.6 on 2023-11-28 19:06

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_platform_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='store_key',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='store key'),
        ),
    ]
