# Generated by Django 4.1.6 on 2023-11-24 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
        ('integration', '0009_onboarding_locations_alter_onboarding_store_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onboarding',
            name='client',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='integration.platform', verbose_name='Platform'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='locations',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='food.location', verbose_name='locations'),
        ),
        migrations.AlterField(
            model_name='onboarding',
            name='onboarding',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='restaurant'),
        ),
    ]
