# Generated by Django 4.1.6 on 2023-11-30 04:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0009_alter_onboarding_store_key'),
        ('integration', '0010_alter_onboarding_client_alter_onboarding_locations_and_more'),
    ]

    operations = [
    ]
