# Generated by Django 4.1.6 on 2024-11-24 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0108_menuitem_allow_group_order'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0119_order_is_group_order'),
        ('accounts', '0031_user_agree'),
        ('remotekitchen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('group_start_at', models.DateTimeField(auto_now_add=True, verbose_name='group order started at')),
                ('group_end_at', models.DateTimeField(blank=True, null=True, verbose_name='group order end at')),
                ('invite_code', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='company')),
                ('joined_users', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='joined users')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location')),
                ('orders', models.ManyToManyField(blank=True, to='billing.order', verbose_name='confirm orders')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
