# Generated by Django 4.1.6 on 2024-12-09 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotekitchen', '0004_searchkeyword'),
    ]

    operations = [
        migrations.RenameField(
            model_name='searchkeyword',
            old_name='creates_at',
            new_name='created_at',
        ),
    ]
