# Generated by Django 4.1.6 on 2024-12-23 06:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('remotekitchen', '0008_useraddressrk'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddressRK',
        ),
    ]
