# Generated by Django 4.1.6 on 2025-03-06 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0128_merge_20250211_0424'),
        ('remotekitchen', '0011_countdown'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFeeRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_order_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('second_order_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('third_or_more_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('restaurants', models.ManyToManyField(blank=True, to='food.restaurant')),
            ],
        ),
    ]
