# Generated by Django 4.1.6 on 2023-06-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('dish_name', models.TextField(blank=True, null=True, verbose_name='Dish name')),
                ('dish_description', models.TextField(blank=True, null=True, verbose_name='Dish description')),
                ('price', models.TextField(blank=True, null=True, verbose_name='Price')),
                ('weblink', models.TextField(blank=True, null=True, verbose_name='Web link')),
                ('drivelink', models.TextField(blank=True, null=True, verbose_name='Drive link')),
                ('store_name', models.TextField(blank=True, null=True, verbose_name='Store Name')),
                ('platform', models.TextField(blank=True, null=True, verbose_name='Platform')),
                ('rating', models.TextField(blank=True, null=True, verbose_name='Rating')),
                ('star', models.TextField(blank=True, null=True, verbose_name='Star')),
                ('address', models.TextField(blank=True, null=True, verbose_name='Address')),
                ('store_link', models.TextField(blank=True, null=True, verbose_name='Store link')),
                ('cuisine_category', models.TextField(blank=True, null=True, verbose_name='Cuisine category')),
            ],
            options={
                'verbose_name': 'Image Url',
                'verbose_name_plural': 'Image Urls',
            },
        ),
    ]
