# Generated by Django 4.1.6 on 2023-07-07 19:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0028_remove_orderitem_menu_item_remove_orderitem_order_and_more'),
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_fee',
            field=models.FloatField(default=0, verbose_name='Delivery fee'),
        ),
        migrations.AddField(
            model_name='order',
            name='dropoff_address',
            field=models.TextField(blank=True, verbose_name='Dropoff Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='dropoff_location',
            field=models.JSONField(default=dict, verbose_name='Dropoff location'),
        ),
        migrations.AddField(
            model_name='order',
            name='dropoff_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Dropoff phone number'),
        ),
        migrations.AddField(
            model_name='order',
            name='extra',
            field=models.JSONField(default=dict, verbose_name='Extra'),
        ),
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location'),
        ),
    ]
