# Generated by Django 4.1.6 on 2023-07-10 19:53

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_order_delivery_fee_order_dropoff_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Order ID'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('rider_confirmed', 'RIDER_CONFIRMED'), ('rider_confirmed_pickup_arrival', 'RIDER_CONFIRMED'), ('rider_picked_up', 'RIDER_PICKED_UP'), ('rider_confirmed_dropoff_arrival', 'RIDER_CONFIRMED_DROPOFF_ARRIVAL'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
