# Generated by Django 4.1.6 on 2023-07-18 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_address'),
        ('billing', '0003_alter_order_order_id_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, verbose_name='Cancellation reason'),
        ),
        migrations.AddField(
            model_name='order',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery time'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address',
            field=models.TextField(blank=True, verbose_name='Pickup Address'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pickup Time'),
        ),
    ]
