# Generated by Django 4.1.6 on 2023-07-19 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_order_cancellation_reason_order_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_url',
            field=models.URLField(blank=True, verbose_name='Tracking URL'),
        ),
    ]
