# Generated by Django 4.1.6 on 2023-07-20 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_order_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='support_reference',
            field=models.CharField(blank=True, max_length=100, verbose_name='Support Reference'),
        ),
        migrations.AddField(
            model_name='order',
            name='tips',
            field=models.FloatField(default=0, verbose_name='Tips'),
        ),
    ]
