# Generated by Django 4.1.6 on 2023-08-08 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0009_paypalcapturepayload_uid_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('paypal_email', models.EmailField(blank=True, max_length=254, verbose_name='Paypal Email')),
                ('paypal_merchant_id', models.CharField(blank=True, max_length=20, verbose_name='Paypal Merchant ID')),
            ],
            options={
                'verbose_name': 'Payment Details',
                'verbose_name_plural': 'Payment Details',
            },
        ),
    ]
