# Generated by Django 4.1.6 on 2023-08-09 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_address'),
        ('billing', '0010_paymentdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='company',
            field=models.ForeignKey(default=27, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
            preserve_default=False,
        ),
    ]
