# Generated by Django 4.1.6 on 2023-08-11 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0011_paymentdetails_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='title',
            field=models.CharField(blank=True, max_length=250, verbose_name='Title'),
        ),
    ]
