# Generated by Django 4.1.6 on 2023-08-17 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0012_paymentdetails_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('ready_for_pickup', 'READY_FOR_PICKUP'), ('rider_confirmed', 'RIDER_CONFIRMED'), ('rider_confirmed_pickup_arrival', 'RIDER_CONFIRMED'), ('rider_picked_up', 'RIDER_PICKED_UP'), ('rider_confirmed_dropoff_arrival', 'RIDER_CONFIRMED_DROPOFF_ARRIVAL'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
