# Generated by Django 4.1.6 on 2023-08-21 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0013_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='purchase',
            name='order',
        ),
        migrations.AddField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.purchase', verbose_name='Purchase'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('ready_for_pickup', 'READY_FOR_PICKUP'), ('rider_confirmed', 'RIDER_CONFIRMED'), ('rider_confirmed_pickup_arrival', 'RIDER_CONFIRMED'), ('rider_picked_up', 'RIDER_PICKED_UP'), ('rider_confirmed_dropoff_arrival', 'RIDER_CONFIRMED_DROPOFF_ARRIVAL'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
