# Generated by Django 4.1.6 on 2023-08-28 21:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0014_remove_purchase_order_order_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='purchase_state',
            field=models.CharField(choices=[('purchased', 'PURCHASED'), ('cancelled', 'CANCELLED'), ('pending', 'PENDING')], default='pending', max_length=30, verbose_name='Purchase State'),
        ),
        migrations.CreateModel(
            name='StripeCapturePayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('payload', models.JSONField(default=dict, verbose_name='Payload')),
                ('uid', models.CharField(blank=True, max_length=250, verbose_name='UID')),
                ('purchase', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.purchase', verbose_name='Purchase')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stripe_payloads', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Stripe Capture Payload',
                'verbose_name_plural': 'Stripe Capture Payloads',
            },
        ),
    ]
