# Generated by Django 4.1.6 on 2023-09-01 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0015_purchase_purchase_state_stripecapturepayload'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentdetails',
            name='account_holder_name',
            field=models.CharField(blank=True, max_length=250, verbose_name='Account Holder Name'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='account_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Account Number'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='country',
            field=models.CharField(blank=True, max_length=40, verbose_name='Country'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='currency',
            field=models.CharField(blank=True, max_length=10, verbose_name='Currency'),
        ),
        migrations.AddField(
            model_name='paymentdetails',
            name='routing_number',
            field=models.CharField(blank=True, max_length=50, verbose_name='Routing Number'),
        ),
    ]
