# Generated by Django 4.1.6 on 2023-09-05 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0016_paymentdetails_account_holder_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_platform',
            field=models.CharField(choices=[('doordash', 'DOORDASH'), ('ubereats', 'UBEREATS')], default='doordash', max_length=30, verbose_name='Delivery platform'),
        ),
        migrations.AddField(
            model_name='order',
            name='dropoff_contact_first_name',
            field=models.TextField(blank=True, verbose_name='Dropoff contact first name'),
        ),
        migrations.AddField(
            model_name='order',
            name='dropoff_contact_last_name',
            field=models.TextField(blank=True, verbose_name='Dropoff contact last name'),
        ),
    ]
