# Generated by Django 4.1.6 on 2023-09-14 19:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0033_openinghour_is_close_restaurant_email_and_more'),
        ('accounts', '0009_user_address'),
        ('billing', '0017_order_delivery_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('invoice_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Invoice ID')),
                ('invoice_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Invoice date')),
                ('due_date', models.DateTimeField(blank=True, null=True, verbose_name='Due date')),
                ('is_paid', models.BooleanField(default=False, verbose_name='Is paid')),
                ('total_amount', models.FloatField(default=0, verbose_name='Total amount')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Invoice',
                'verbose_name_plural': 'Invoices',
            },
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('unit_price', models.FloatField(default=0, verbose_name='Unit price')),
                ('subtotal', models.FloatField(default=0, verbose_name='Subtotal')),
                ('invoice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.invoice', verbose_name='Invoice')),
                ('menu_item', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.menuitem', verbose_name='Menu Item')),
            ],
            options={
                'verbose_name': 'Invoice Item',
                'verbose_name_plural': 'Invoice Items',
            },
        ),
    ]
