# Generated by Django 4.1.6 on 2023-09-15 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0018_invoice_invoiceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchase',
            name='extra',
            field=models.JSONField(blank=True, default=dict, verbose_name='Extra'),
        ),
    ]
