# Generated by Django 4.1.6 on 2023-09-19 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0019_purchase_extra'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invoiceitem',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='invoiceitem',
            name='item',
            field=models.CharField(blank=True, max_length=250, verbose_name='Menu Item'),
        ),
    ]
