# Generated by Django 4.1.6 on 2023-09-26 18:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0020_remove_invoiceitem_menu_item_invoiceitem_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeConnectAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('stripe_id', models.TextField(verbose_name='Stripe ID')),
                ('account_details', models.JSONField(blank=True, default=dict, verbose_name='Account details')),
                ('charges_enabled', models.BooleanField(default=False, verbose_name='Charges enabled')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Stripe Connect Account',
                'verbose_name_plural': 'Stripe Connect Accounts',
            },
        ),
    ]
