# Generated by Django 4.1.6 on 2023-09-27 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0036_location_doordash_external_store_id_location_email_and_more'),
        ('accounts', '0009_user_address'),
        ('billing', '0021_stripeconnectaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryFeeAssociation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('delivery_fee', models.FloatField(default=0, verbose_name='Delivery_fee')),
                ('convenience_fee', models.FloatField(default=0, verbose_name='Convenience_fee')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
                ('discount_in_percent', models.BooleanField(default=0, verbose_name='Discount By Percent')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Delivery Fees Association',
            },
        ),
    ]
