# Generated by Django 4.1.6 on 2023-09-27 20:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0021_stripeconnectaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='stripeconnectaccount',
            name='company',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stripeconnectaccount',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
