# Generated by Django 4.1.6 on 2023-10-05 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_deliveryfeeassociation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryfeeassociation',
            name='discount_in_percent',
            field=models.BooleanField(default=0, verbose_name='Give Discount'),
        ),
    ]
