# Generated by Django 4.1.6 on 2023-10-05 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0023_alter_deliveryfeeassociation_discount_in_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryfeeassociation',
            name='discount_in_percent',
        ),
        migrations.AddField(
            model_name='deliveryfeeassociation',
            name='minimum_order_amount',
            field=models.FloatField(default=0, verbose_name='Minimum Order Amount'),
        ),
        migrations.AddField(
            model_name='deliveryfeeassociation',
            name='tax_rate',
            field=models.FloatField(default=0, verbose_name='Tax Rate'),
        ),
        migrations.AddField(
            model_name='deliveryfeeassociation',
            name='use_tax',
            field=models.BooleanField(default=0, verbose_name='Use Tax'),
        ),
    ]
