# Generated by Django 4.1.6 on 2023-09-30 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0022_deliveryfeeassociation'),
        ('billing', '0023_billingprofile'),
    ]

    operations = [
    ]
