# Generated by Django 4.1.6 on 2023-09-29 23:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_address'),
        ('billing', '0024_merge_0022_deliveryfeeassociation_0023_billingprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingprofile',
            name='currency',
            field=models.CharField(blank=True, default='USD', max_length=10, verbose_name='currency'),
        ),
        migrations.AddField(
            model_name='order',
            name='total',
            field=models.FloatField(default=0, verbose_name='Total'),
        ),
        migrations.AlterField(
            model_name='deliveryfeeassociation',
            name='discount_in_percent',
            field=models.BooleanField(default=0, verbose_name='Give Discount'),
        ),
        migrations.AlterField(
            model_name='purchase',
            name='purchase_state',
            field=models.CharField(choices=[('purchased', 'PURCHASED'), ('cancelled', 'CANCELLED'), ('pending', 'PENDING'), ('refunded', 'REFUNDED')], default='pending', max_length=30, verbose_name='Purchase State'),
        ),
        migrations.CreateModel(
            name='Payout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('uid', models.TextField(blank=True, verbose_name='Payout ID')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('chatchef_commission', models.FloatField(default=0, verbose_name='Chatchef commission')),
                ('details', models.JSONField(default=dict, verbose_name='Details')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Payout',
                'verbose_name_plural': 'Payouts',
            },
        ),
    ]
