# Generated by Django 4.1.6 on 2023-10-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0025_alter_deliveryfeeassociation_discount_in_percent'),
        ('billing', '0025_billingprofile_currency_order_total_and_more'),
    ]

    operations = [
    ]
