# Generated by Django 4.1.6 on 2023-10-06 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0024_remove_deliveryfeeassociation_discount_in_percent_and_more'),
        ('billing', '0026_merge_20231004_0411'),
    ]

    operations = [
    ]
