# Generated by Django 4.1.6 on 2023-10-09 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0027_merge_20231006_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dropoff_address',
            field=models.TextField(blank=True, verbose_name='Dropoff  Address'),
        ),
    ]
