# Generated by Django 4.1.6 on 2023-10-09 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0028_alter_order_dropoff_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dropoff_address',
            field=models.TextField(blank=True, verbose_name='Dropoff Address'),
        ),
    ]
