# Generated by Django 4.1.6 on 2023-11-02 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0053_alter_timetable_opening_hour'),
        ('billing', '0030_order_convenience_fee_order_tax_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pos_data',
            field=models.ManyToManyField(blank=True, to='food.pos_data', verbose_name='pos details'),
        ),
    ]
