# Generated by Django 4.1.6 on 2023-11-08 22:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0007_birthdaygift'),
        ('billing', '0031_order_pos_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount',
            field=models.FloatField(default=0, verbose_name='Discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.voucher', verbose_name='Voucher'),
        ),
    ]
