# Generated by Django 4.1.6 on 2023-11-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0032_order_discount_order_voucher'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_method',
            field=models.CharField(choices=[('asap', 'ASAP'), ('scheduled', 'SCHEDULED'), ('delivery', 'DELIVERY'), ('restaurant_delivery', 'RESTAURANT_DELIVERY'), ('pickup', 'PICKUP'), ('dine_in', 'DINE_IN')], default='delivery', max_length=20, verbose_name='Order method'),
        ),
        migrations.AlterField(
            model_name='order',
            name='delivery_platform',
            field=models.CharField(blank=True, choices=[('doordash', 'DOORDASH'), ('ubereats', 'UBEREATS')], default='doordash', max_length=30, verbose_name='Delivery platform'),
        ),
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=True, verbose_name='Is paid'),
        ),
    ]
