# Generated by Django 4.1.6 on 2023-11-15 19:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
        ('billing', '0033_order_order_method_alter_order_delivery_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModifiersItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('modifiersOrderItems', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifier_item', to='food.menuitem', verbose_name='modifier item')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='OrderedModifiers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('modifiers', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='food.modifiergroup', verbose_name='modifiers details')),
                ('modifiersItems', models.ManyToManyField(related_name='modifiers_items', to='billing.ordermodifiersitems', verbose_name='modifiers items')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
                'ordering': ['-id'],
            },
        ),
    ]
