# Generated by Django 4.1.6 on 2023-11-15 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0034_ordermodifiersitems_orderedmodifiers'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='modifiers',
            field=models.ManyToManyField(to='billing.orderedmodifiers', verbose_name='modifiers'),
        ),
    ]
