# Generated by Django 4.1.6 on 2023-11-15 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0035_orderitem_modifiers'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderedmodifiers',
            options={'ordering': ['-id'], 'verbose_name': 'Ordered Modifiers', 'verbose_name_plural': 'Ordered Modifiers'},
        ),
        migrations.AlterModelOptions(
            name='ordermodifiersitems',
            options={'ordering': ['-id'], 'verbose_name': 'Order Modifiers Item', 'verbose_name_plural': 'Order Modifiers Items'},
        ),
    ]
