# Generated by Django 4.1.6 on 2023-11-16 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0036_alter_orderedmodifiers_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduling_type',
            field=models.CharField(choices=[('asap', 'ASAP'), ('fixed_time', 'FIXED_TIME')], default='asap', max_length=20, verbose_name='scheduling type'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_method',
            field=models.CharField(choices=[('scheduled', 'SCHEDULED'), ('delivery', 'DELIVERY'), ('restaurant_delivery', 'RESTAURANT_DELIVERY'), ('pickup', 'PICKUP'), ('dine_in', 'DINE_IN')], default='delivery', max_length=20, verbose_name='Order method'),
        ),
    ]
