# Generated by Django 4.1.6 on 2023-11-20 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0037_order_scheduling_type_alter_order_order_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='modifiers',
            field=models.ManyToManyField(null=True, to='billing.orderedmodifiers', verbose_name='modifiers'),
        ),
    ]
