# Generated by Django 4.1.6 on 2023-11-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0038_alter_orderitem_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='modifiers',
            field=models.ManyToManyField(blank=True, null=True, to='billing.orderedmodifiers', verbose_name='modifiers'),
        ),
    ]
