# Generated by Django 4.1.6 on 2023-11-20 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0039_alter_orderitem_modifiers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitem',
            name='modifiers',
            field=models.ManyToManyField(blank=True, to='billing.orderedmodifiers', verbose_name='modifiers'),
        ),
        migrations.AlterField(
            model_name='ordermodifiersitems',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Quantity'),
        ),
    ]
