# Generated by Django 4.1.6 on 2023-11-20 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0040_alter_orderitem_modifiers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedmodifiers',
            name='modifiersItems',
            field=models.ManyToManyField(blank=True, related_name='modifiers_items', to='billing.ordermodifiersitems', verbose_name='modifiers items'),
        ),
    ]
