# Generated by Django 4.1.6 on 2023-11-24 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('integration', '0008_platform_mode'),
        ('billing', '0041_alter_orderedmodifiers_modifiersitems'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='external_platform',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='integration.platform', verbose_name='partners identifier'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_type',
            field=models.CharField(choices=[('internal', 'INTERNAL'), ('external', 'EXTERNAL')], default='internal', max_length=255, verbose_name='order type'),
        ),
    ]
