# Generated by Django 4.1.6 on 2023-11-28 15:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0042_order_external_platform_order_order_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalPaymentInformation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('value', models.FloatField(verbose_name='order value')),
                ('processingStatus', models.CharField(choices=[('COLLECTABLE', 'COLLECTABLE'), ('PROCESSED', 'PROCESSED')], max_length=50, verbose_name='processing status')),
                ('paymentMethod', models.CharField(choices=[('CASH', 'CASH'), ('CARD', 'CARD'), ('UNKNOWN', 'UNKNOWN'), ('OTHER', 'OTHER'), ('CHEQUE', 'CHEQUE')], max_length=50, verbose_name='payment method')),
                ('paymentAuthorizer', models.CharField(blank=True, choices=[('UNKNOWN_TYPE', 'UNKNOWN_TYPE'), ('OTHER_TYPE', 'OTHER_TYPE'), ('MASTERCARD', 'MASTERCARD'), ('MASTERCARD_MAESTRO', 'MASTERCARD_MAESTRO'), ('MASTERCARD_DEBIT', 'MASTERCARD_DEBIT'), ('VISA', 'VISA'), ('VISA_DEBIT', 'VISA_DEBIT'), ('AMEX', 'AMEX'), ('VISA_ELECTORN', 'VISA_ELECTORN'), ('DINERS', 'DINERS'), ('ELO', 'ELO'), ('ELO_DEBIT', 'ELO_DEBIT'), ('HIPERCARD', 'HIPERCARD'), ('BANRICOMPRAS', 'BANRICOMPRAS'), ('BANRICOMPRAS_DEBIT', 'BANRICOMPRAS_DEBIT'), ('NUGO', 'NUGO'), ('GOODCARD', 'GOODCARD'), ('VERDECARD', 'VERDECARD'), ('CARNET', 'CARNET'), ('CHEF_CARD', 'CHEF_CARD'), ('GER_CC_CREDITO', 'GER_CC_CREDITO'), ('TERMINAL_BANCARIA', 'TERMINAL_BANCARIA'), ('DEBIT', 'DEBIT'), ('QR_CODE', 'QR_CODE'), ('RAPPI_PAY', 'RAPPI_PAY'), ('DISCOVER', 'DISCOVER'), ('VALE_GREEN_CARD_PAPEL', 'VALE_GREEN_CARD_PAPEL'), ('VALE_GREEN_CARD_CARD', 'VALE_GREEN_CARD_CARD'), ('VALE_REFEISUL', 'VALE_REFEISUL'), ('VALE_VEROCARD', 'VALE_VEROCARD'), ('VALE_VR_SMART', 'VALE_VR_SMART'), ('VALE_SODEXO', 'VALE_SODEXO'), ('VALE_TICKET_RESTAURANTE', 'VALE_TICKET_RESTAURANTE'), ('VALE_ALELO', 'VALE_ALELO'), ('VALE_BEN_VIS', 'VALE_BEN_VIS'), ('VALE_COOPER_CARD', 'VALE_COOPER_CARD'), ('NUTRICARD_REFEICAO_E_ALIMENTACAO', 'NUTRICARD_REFEICAO_E_ALIMENTACAO'), ('APPLE_PAY_MASTERCARD', 'APPLE_PAY_MASTERCARD'), ('APPLE_PAY_VISA', 'APPLE_PAY_VISA'), ('APPLE_PAY_AMEX', 'APPLE_PAY_AMEX'), ('GOOGLE_PAY_ELO', 'GOOGLE_PAY_ELO'), ('GOOGLE_PAY_MASTERCARD', 'GOOGLE_PAY_MASTERCARD'), ('GOOGLE_PAY_VISA', 'GOOGLE_PAY_VISA'), ('MOVILE_PAY', 'MOVILE_PAY'), ('MOVILE_PAY_AMEX', 'MOVILE_PAY_AMEX'), ('MOVILE_PAY_DINERS', 'MOVILE_PAY_DINERS'), ('MOVILE_PAY_ELO', 'MOVILE_PAY_ELO'), ('MOVILE_PAY_HIPERCARD', 'MOVILE_PAY_HIPERCARD'), ('MOVILE_PAY_MASTERCARD', 'MOVILE_PAY_MASTERCARD'), ('MOVILE_PAY_VISA', 'MOVILE_PAY_VISA'), ('IFOOD_CORP', 'IFOOD_CORP'), ('LOOP_CLUB', 'LOOP_CLUB'), ('PAYPAL', 'PAYPAL'), ('PSE', 'PSE'), ('PIX', 'PIX')], max_length=50, null=True, verbose_name='payment authorizer')),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='externalPayments', to='billing.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'External Payment Information',
                'verbose_name_plural': 'External Payments Information',
            },
        ),
    ]
