# Generated by Django 4.1.6 on 2023-12-01 22:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_fissioncampaign_color_ratingandreview'),
        ('billing', '0043_externalpaymentinformation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bogo',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.bogo', verbose_name='Bogo'),
        ),
    ]
