# Generated by Django 4.1.6 on 2023-12-20 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0008_alter_userreward_user'),
        ('billing', '0044_order_bogo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reward_coupon',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='reward.userreward', verbose_name='Reward Coupon'),
        ),
    ]
