# Generated by Django 4.1.6 on 2023-12-29 16:39

import billing.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0045_order_reward_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='scheduled_time',
            field=models.DateTimeField(blank=True, null=True, validators=[billing.models.Order.validate_future_date], verbose_name='scheduled time'),
        ),
    ]
