# Generated by Django 4.1.6 on 2023-12-29 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0009_alter_additionalcondition_reward_group'),
        ('marketing', '0032_alter_emailconfiguration_email_use_tls'),
        ('billing', '0046_order_scheduled_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='bogo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.bogo', verbose_name='Bogo'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.purchase', verbose_name='Purchase'),
        ),
        migrations.AlterField(
            model_name='order',
            name='reward_coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reward.userreward', verbose_name='Reward Coupon'),
        ),
        migrations.AlterField(
            model_name='order',
            name='voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.voucher', verbose_name='Voucher'),
        ),
    ]
