# Generated by Django 4.1.6 on 2024-01-12 17:09

import billing.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0048_alter_order_order_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='phone')),
                ('is_ordered', models.BooleanField(default=False)),
                ('is_rescheduled', models.BooleanField(default=False)),
                ('is_mailed', models.BooleanField(default=False)),
                ('is_sms_send', models.BooleanField(default=False)),
                ('order_data', models.JSONField(default=dict, verbose_name='order data')),
                ('reminder_time', models.DateTimeField(validators=[billing.models.OrderReminder.validate_future_date], verbose_name='scheduled time')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
