# Generated by Django 4.1.6 on 2024-01-10 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0048_alter_order_order_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Rufund Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='status_before_cancelled',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('ready_for_pickup', 'READY_FOR_PICKUP'), ('rider_confirmed', 'RIDER_CONFIRMED'), ('rider_confirmed_pickup_arrival', 'RIDER_CONFIRMED'), ('rider_picked_up', 'RIDER_PICKED_UP'), ('rider_confirmed_dropoff_arrival', 'RIDER_CONFIRMED_DROPOFF_ARRIVAL'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('n/a', 'N/A')], default='n/a', max_length=50, verbose_name='Status before cancelled'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('ready_for_pickup', 'READY_FOR_PICKUP'), ('rider_confirmed', 'RIDER_CONFIRMED'), ('rider_confirmed_pickup_arrival', 'RIDER_CONFIRMED'), ('rider_picked_up', 'RIDER_PICKED_UP'), ('rider_confirmed_dropoff_arrival', 'RIDER_CONFIRMED_DROPOFF_ARRIVAL'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('n/a', 'N/A')], default='pending', max_length=50, verbose_name='Status'),
        ),
    ]
