# Generated by Django 4.1.6 on 2024-01-11 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0049_order_refund_amount_order_status_before_cancelled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='refund_amount',
            field=models.FloatField(blank=True, default=0, verbose_name='Refund Amount'),
        ),
    ]
