# Generated by Django 4.1.6 on 2024-01-16 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0036_merge_20240115_1404'),
        ('food', '0061_alter_menu_options_menu_showing'),
        ('billing', '0050_alter_order_refund_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='spend_x_save_y',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.spendxsavey', verbose_name='Spend X Save Y offer'),
        ),
        migrations.AddField(
            model_name='purchase',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant'),
        ),
    ]
