# Generated by Django 4.1.6 on 2024-01-17 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0051_order_spend_x_save_y_purchase_restaurant'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='purchase',
            options={'ordering': ['-id'], 'verbose_name': 'Purchase', 'verbose_name_plural': 'Purchases'},
        ),
    ]
