# Generated by Django 4.1.6 on 2024-01-19 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0049_orderreminder'),
        ('billing', '0052_alter_purchase_options'),
    ]

    operations = [
    ]
