# Generated by Django 4.1.6 on 2024-01-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0053_merge_0049_orderreminder_0052_alter_purchase_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='is_paid',
            field=models.BooleanField(default=False, verbose_name='Is paid'),
        ),
    ]
