# Generated by Django 4.1.6 on 2024-01-23 05:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_useraddress_is_default'),
        ('food', '0061_alter_menu_options_menu_showing'),
        ('billing', '0053_merge_0049_orderreminder_0052_alter_purchase_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderreminder',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='company'),
        ),
        migrations.AddField(
            model_name='orderreminder',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='orderreminder',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant'),
        ),
    ]
