# Generated by Django 4.1.6 on 2024-01-23 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0054_alter_order_is_paid'),
        ('billing', '0054_orderreminder_company_orderreminder_location_and_more'),
    ]

    operations = [
    ]
