# Generated by Django 4.1.6 on 2024-01-26 14:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0054_orderreminder_company_orderreminder_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('pin', models.CharField(blank=True, max_length=20, null=True, verbose_name='pin')),
                ('balance', models.FloatField(default=0, verbose_name='balance')),
                ('wallet_address', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='wallet address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='wallet user')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('transaction_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='transaction id')),
                ('amount', models.FloatField(verbose_name='balance')),
                ('charges', models.FloatField(default=0, verbose_name='charges')),
                ('currency', models.CharField(blank=True, max_length=50, null=True, verbose_name='currency')),
                ('type', models.CharField(blank=True, choices=[('in', 'IN'), ('out', 'OUT')], default='in', max_length=50, null=True, verbose_name='transaction type')),
                ('status', models.CharField(blank=True, choices=[('pending', 'PENDING'), ('success', 'SUCCESS'), ('failed', 'FAILED')], default='pending', max_length=50, null=True, verbose_name='transaction status')),
                ('gateway', models.CharField(blank=True, choices=[('unknown', 'UNKNOWN'), ('stripe', 'STRIPE'), ('paypal', 'PAYPAL')], default='unknown', max_length=50, null=True, verbose_name='gateway')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('wallet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.wallet', verbose_name='wallet')),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'ordering': ['-id'],
            },
        ),
    ]
