# Generated by Django 4.1.6 on 2024-01-26 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0055_wallet_transactions'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='gateway_transaction_id',
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name='gateway transaction id'),
        ),
    ]
