# Generated by Django 4.1.6 on 2024-01-26 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0055_merge_20240123_1133'),
        ('billing', '0056_transactions_gateway_transaction_id'),
    ]

    operations = [
    ]
