# Generated by Django 4.1.6 on 2024-02-09 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address'),
        ('billing', '0057_merge_20240126_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dropoff_address_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_dropoff', to='core.address', verbose_name='Dropoff Address Details'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_address_details',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pickup', to='core.address', verbose_name='Pickup Address Details'),
        ),
    ]
