# Generated by Django 4.1.6 on 2024-01-30 06:42

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0061_alter_menu_options_menu_showing'),
        ('billing', '0059_transactions_location'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='wallet',
            unique_together={('user', 'restaurant')},
        ),
    ]
