# Generated by Django 4.1.6 on 2024-02-06 04:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0061_alter_menu_options_menu_showing'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('billing', '0060_alter_wallet_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=500, verbose_name='card number')),
                ('expire_date', models.CharField(max_length=500, verbose_name='expire_date')),
                ('cvv', models.CharField(max_length=500, verbose_name='cvv')),
                ('name_on_card', models.CharField(max_length=500, verbose_name='card holder')),
                ('address_line_1', models.CharField(max_length=500, verbose_name='address line 1')),
                ('address_line_2', models.CharField(max_length=500, verbose_name='address line 2')),
                ('country', models.CharField(max_length=500, verbose_name='country')),
                ('city', models.CharField(max_length=500, verbose_name='city')),
                ('postal_code', models.CharField(max_length=500, verbose_name='postal code')),
                ('state', models.CharField(max_length=50, verbose_name='state')),
                ('uid', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='uid')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Payment Methods',
                'verbose_name_plural': 'Payment Methods',
                'ordering': ['-id'],
            },
        ),
    ]
