# Generated by Django 4.1.6 on 2024-02-14 11:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0058_order_dropoff_address_details_and_more'),
        ('billing', '0061_paymentmethods'),
    ]

    operations = [
    ]
