# Generated by Django 4.1.6 on 2024-03-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0062_merge_20240214_0300'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_discount',
            field=models.FloatField(default=0, verbose_name='Delivery fee'),
        ),
        migrations.AddField(
            model_name='order',
            name='original_delivery_fee',
            field=models.FloatField(default=0, verbose_name='Delivery fee'),
        ),
    ]
