# Generated by Django 4.1.6 on 2024-03-11 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0063_order_delivery_discount_order_original_delivery_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_discount',
            field=models.FloatField(default=0, verbose_name='Delivery discount'),
        ),
        migrations.AlterField(
            model_name='order',
            name='original_delivery_fee',
            field=models.FloatField(default=0, verbose_name='original delivery fee'),
        ),
    ]
