# Generated by Django 4.1.6 on 2024-03-14 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0064_alter_order_delivery_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='dasher_dropoff_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Dasher Dropoff Phone Number'),
        ),
        migrations.AddField(
            model_name='order',
            name='dasher_pickup_phone_number',
            field=models.CharField(blank=True, max_length=20, verbose_name='Dasher Pickup phone number'),
        ),
    ]
