# Generated by Django 4.1.6 on 2024-04-11 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0066_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'STRIPE'), ('card', 'CARD'), ('paypal', 'PAYPAL'), ('cash', 'CASH')], default='stripe', max_length=30, verbose_name='Payment method'),
        ),
    ]
