# Generated by Django 4.1.6 on 2024-04-12 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0067_order_payment_method'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_platform',
            field=models.CharField(blank=True, choices=[('doordash', 'DOORDASH'), ('ubereats', 'UBEREATS'), ('n/a', 'N/A')], default='n/a', max_length=30, verbose_name='Delivery platform'),
        ),
    ]
