# Generated by Django 4.1.6 on 2024-04-17 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0068_alter_order_delivery_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bag_price',
            field=models.FloatField(default=0, verbose_name='bag price'),
        ),
    ]
