# Generated by Django 4.1.6 on 2024-04-18 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0069_order_bag_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_bag',
            field=models.BooleanField(default=False, verbose_name='is bag'),
        ),
    ]
