# Generated by Django 4.1.6 on 2024-04-18 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0070_order_is_bag'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tips_for_restaurant',
            field=models.FloatField(default=0, verbose_name='Tips for restaurant'),
        ),
    ]
