# Generated by Django 4.1.6 on 2024-04-24 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0071_order_tips_for_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('ready_for_pickup', 'READY_FOR_PICKUP'), ('rider_confirmed', 'RIDER_CONFIRMED'), ('rider_confirmed_pickup_arrival', 'RIDER_CONFIRMED_PICKUP_ARRIVAL'), ('rider_picked_up', 'RIDER_PICKED_UP'), ('rider_confirmed_dropoff_arrival', 'RIDER_CONFIRMED_DROPOFF_ARRIVAL'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('rejected', 'REJECTED'), ('n/a', 'N/A')], default='pending', max_length=50, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status_before_cancelled',
            field=models.CharField(blank=True, choices=[('pending', 'PENDING'), ('accepted', 'ACCEPTED'), ('ready_for_pickup', 'READY_FOR_PICKUP'), ('rider_confirmed', 'RIDER_CONFIRMED'), ('rider_confirmed_pickup_arrival', 'RIDER_CONFIRMED_PICKUP_ARRIVAL'), ('rider_picked_up', 'RIDER_PICKED_UP'), ('rider_confirmed_dropoff_arrival', 'RIDER_CONFIRMED_DROPOFF_ARRIVAL'), ('completed', 'COMPLETED'), ('cancelled', 'CANCELLED'), ('rejected', 'REJECTED'), ('n/a', 'N/A')], default='n/a', max_length=50, verbose_name='Status before cancelled'),
        ),
    ]
