# Generated by Django 4.1.6 on 2024-04-27 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0072_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='currency',
            field=models.CharField(default='cad', max_length=200, verbose_name='Currency'),
        ),
    ]
