# Generated by Django 4.1.6 on 2024-04-29 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0073_alter_order_currency'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_utensil',
            field=models.BooleanField(default=False, verbose_name='is utensil'),
        ),
        migrations.AddField(
            model_name='order',
            name='utensil_price',
            field=models.FloatField(default=0, verbose_name='utensil price'),
        ),
    ]
