# Generated by Django 4.1.6 on 2024-04-30 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0074_order_is_utensil_order_utensil_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='is_utensil',
        ),
        migrations.AddField(
            model_name='order',
            name='utensil_quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='utensil quantity'),
        ),
    ]
