# Generated by Django 4.1.6 on 2024-05-03 17:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0076_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='doordash_external_delivery_id',
            field=models.UUIDField(default=uuid.uuid4, null=True, verbose_name='Doordash External Delivery ID'),
        ),
    ]
