# Generated by Django 4.1.6 on 2024-05-03 17:46
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("billing", "Order")
    for row in MyModel.objects.all():
        row.doordash_external_delivery_id = row.order_id
        row.save(update_fields=["doordash_external_delivery_id"])


class Migration(migrations.Migration):
    dependencies = [
        ('billing', '0077_order_doordash_external_delivery_id'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
