# Generated by Django 4.1.6 on 2024-05-03 17:46
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0078_auto_20240503_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='doordash_external_delivery_id',
            field=models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='Doordash External Delivery ID'),
        ),
    ]
