# Generated by Django 4.1.6 on 2024-05-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0079_auto_20240503_1046'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='prep_time',
            field=models.IntegerField(default=25, verbose_name='Prep time'),
        ),
    ]
