# Generated by Django 4.1.6 on 2024-05-08 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0080_order_prep_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='uber_delivery_id',
            field=models.TextField(blank=True, verbose_name='Uber Delivery ID'),
        ),
    ]
