# Generated by Django 4.1.6 on 2024-05-15 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0078_remove_restaurant_banner_image_and_more'),
        ('accounts', '0021_restaurantuser_reward_level'),
        ('billing', '0082_alter_order_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantFee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('max_distance', models.FloatField(default=5, verbose_name='Max Distance')),
                ('delivery_fee', models.FloatField(default=1, verbose_name='Delivery Fee')),
                ('service_fee', models.FloatField(default=0, verbose_name='Service Fee')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Restaurant Fee',
                'verbose_name_plural': 'Restaurant Fees',
            },
        ),
    ]
