# Generated by Django 4.1.6 on 2024-05-23 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0083_restaurantfee'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryfeeassociation',
            name='alcoholic_tax_rate',
            field=models.FloatField(default=0, verbose_name='Alcoholic Tax Rate'),
        ),
    ]
