# Generated by Django 4.1.6 on 2024-05-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0084_deliveryfeeassociation_alcoholic_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='checkout_note',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='checkout note'),
        ),
    ]
