# Generated by Django 4.1.6 on 2024-05-24 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0084_deliveryfeeassociation_alcoholic_tax_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='stripe_fee',
            field=models.FloatField(default=0, verbose_name='Stripe Fee'),
        ),
    ]
