# Generated by Django 4.1.6 on 2024-05-28 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appstore_version'),
        ('billing', '0085_order_stripe_fee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='dropoff_address_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_dropoff', to='core.address', verbose_name='Dropoff Address Details'),
        ),
        migrations.AlterField(
            model_name='order',
            name='pickup_address_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_pickup', to='core.address', verbose_name='Pickup Address Details'),
        ),
    ]
