# Generated by Django 4.1.6 on 2024-05-29 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0085_order_checkout_note'),
        ('billing', '0086_alter_order_dropoff_address_details_and_more'),
    ]

    operations = [
    ]
