# Generated by Django 4.1.6 on 2024-06-13 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0087_merge_20240529_0146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='spend_x_save_y',
        ),
    ]
