# Generated by Django 4.1.6 on 2024-06-07 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0087_merge_20240529_0146'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_item_meta_data',
            field=models.JSONField(default=dict, verbose_name='order item meta data'),
        ),
    ]
