# Generated by Django 4.1.6 on 2024-06-14 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0088_order_order_item_meta_data'),
        ('billing', '0088_remove_order_spend_x_save_y'),
    ]

    operations = [
    ]
