# Generated by Django 4.1.6 on 2024-07-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0090_uberauthmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uberauthmodel',
            name='token',
            field=models.TextField(),
        ),
    ]
