# Generated by Django 4.1.6 on 2024-07-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0091_alter_uberauthmodel_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bogo_discount',
            field=models.FloatField(default=0, verbose_name='bogo discount'),
        ),
    ]
