# Generated by Django 4.1.6 on 2024-07-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0092_order_bogo_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='reward_points',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
