# Generated by Django 4.1.6 on 2024-08-02 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0094_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_completed_by_restaurant',
            field=models.BooleanField(default=False),
        ),
    ]
