# Generated by Django 4.1.6 on 2024-08-14 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0097_menuitem_rating'),
        ('billing', '0095_order_is_completed_by_restaurant'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('payout_amount', models.FloatField(default=0)),
                ('invoice', models.FileField(upload_to='invoice/%Y/%m/%d/')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_mailed', models.BooleanField(default=False)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.location')),
                ('orders', models.ManyToManyField(to='billing.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
