# Generated by Django 4.1.6 on 2024-08-15 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0096_payouthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouthistory',
            name='pdf',
            field=models.FileField(default='', upload_to='invoice/pdf/%Y/%m/%d/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payouthistory',
            name='invoice',
            field=models.FileField(upload_to='invoice/xls/%Y/%m/%d/'),
        ),
    ]
