# Generated by Django 4.1.6 on 2024-09-15 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0097_payouthistory_pdf_alter_payouthistory_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouthistory',
            name='bag_fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='statement_end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='statement_start_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='subtotal',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='tax_paid_by_customer',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='tax_paid_by_restaurant',
            field=models.FloatField(default=0),
        ),
    ]
