# Generated by Django 4.1.6 on 2024-09-17 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0098_payouthistory_bag_fees_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payouthistory',
            old_name='subtotal',
            new_name='gross_revenue',
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='net_revenue',
            field=models.FloatField(default=0),
        ),
    ]
