# Generated by Django 4.1.6 on 2024-10-01 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0099_rename_subtotal_payouthistory_gross_revenue_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('stripe', 'STRIPE'), ('card', 'CARD'), ('paypal', 'PAYPAL'), ('cash', 'CASH'), ('wallet', 'WALLET')], default='stripe', max_length=30, verbose_name='Payment method'),
        ),
    ]
