# Generated by Django 4.1.6 on 2024-10-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0102_alter_restaurant_payment_methods_and_more'),
        ('billing', '0100_alter_order_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='gift_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifted_to', to='food.restaurant'),
        ),
        migrations.AddField(
            model_name='transactions',
            name='used_for',
            field=models.CharField(choices=[('gift', 'GIFT'), ('placed_order', 'Placed Order')], default='placed_order', max_length=50, verbose_name='used in'),
        ),
    ]
