# Generated by Django 4.1.6 on 2024-10-14 06:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_contacts'),
        ('billing', '0101_transactions_gift_user_transactions_used_for'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='gift_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifted_to', to='accounts.restaurantuser'),
        ),
    ]
