# Generated by Django 4.1.6 on 2024-10-14 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_contacts'),
        ('billing', '0102_alter_transactions_gift_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='gift_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gifted_by', to='accounts.restaurantuser'),
        ),
    ]
