# Generated by Django 4.1.6 on 2024-10-15 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0103_transactions_gift_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='gateway',
            field=models.CharField(blank=True, choices=[('unknown', 'UNKNOWN'), ('stripe', 'STRIPE'), ('paypal', 'PAYPAL'), ('wallet', 'WALLET')], default='unknown', max_length=50, null=True, verbose_name='gateway'),
        ),
    ]
