# Generated by Django 4.1.6 on 2024-10-20 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0104_alter_transactions_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouthistory',
            name='adjustments',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='adjustments_note',
            field=models.TextField(blank=True, null=True),
        ),
    ]
