# Generated by Django 4.1.6 on 2024-10-20 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0104_alter_transactions_gateway'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouthistory',
            name='uid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
