# Generated by Django 4.1.6 on 2024-10-20 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0105_payouthistory_adjustments_and_more'),
        ('billing', '0105_payouthistory_uid'),
    ]

    operations = [
    ]
