# Generated by Django 4.1.6 on 2024-10-22 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0106_merge_20241020_0351'),
        ('billing', '0106_merge_20241021_1903'),
    ]

    operations = [
    ]
