# Generated by Django 4.1.6 on 2024-10-24 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0107_merge_20241021_2331'),
    ]

    operations = [
        migrations.CreateModel(
            name='RaiderAppAuth',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('token', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
