# Generated by Django 4.1.6 on 2024-10-24 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0108_raiderappauth'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivery_platform',
            field=models.CharField(blank=True, choices=[('doordash', 'DOORDASH'), ('ubereats', 'UBEREATS'), ('raider_app', 'RAIDER_APP'), ('n/a', 'N/A')], default='n/a', max_length=30, verbose_name='Delivery platform'),
        ),
    ]
