# Generated by Django 4.1.6 on 2024-10-30 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0109_alter_order_delivery_platform'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_reason',
            field=models.TextField(blank=True, verbose_name='Refund Reason'),
        ),
    ]
