# Generated by Django 4.1.6 on 2024-10-31 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0110_order_refund_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='raider_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
