# Generated by Django 4.1.6 on 2024-10-31 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0110_order_refund_reason'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouthistory',
            name='delivery_fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='promotional_expenses',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='service_fees_paid_to_chatchef',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='stripe_fees',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='tips',
            field=models.FloatField(default=0),
        ),
    ]
