# Generated by Django 4.1.6 on 2024-10-31 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0111_payouthistory_delivery_fees_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouthistory',
            name='utensil_fees',
            field=models.FloatField(default=0),
        ),
    ]
