# Generated by Django 4.1.6 on 2024-10-31 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0111_order_raider_id'),
        ('billing', '0112_payouthistory_utensil_fees'),
    ]

    operations = [
    ]
