# Generated by Django 4.1.6 on 2024-10-31 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0113_merge_20241031_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouthistory',
            name='original_delivery_fees',
            field=models.FloatField(default=0),
        ),
    ]
