# Generated by Django 4.1.6 on 2024-11-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0114_payouthistory_original_delivery_fees'),
    ]

    operations = [
        migrations.AddField(
            model_name='payouthistory',
            name='delivery_fees_bare_by_restaurant',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistory',
            name='service_fees_paid_by_customer_to_restaurant',
            field=models.FloatField(default=0),
        ),
    ]
