# Generated by Django 4.1.6 on 2024-11-19 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0115_payouthistory_delivery_fees_bare_by_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnregisteredGiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CAD', max_length=10)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('CLAIMED', 'Claimed')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
