# Generated by Django 4.1.6 on 2024-11-19 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0117_unregisteredgiftcard_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregisteredgiftcard',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
