# Generated by Django 4.1.6 on 2024-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0118_alter_unregisteredgiftcard_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_group_order',
            field=models.BooleanField(default=False),
        ),
    ]
