# Generated by Django 4.1.6 on 2024-11-21 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0118_alter_unregisteredgiftcard_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unregisteredgiftcard',
            name='amount',
            field=models.FloatField(default=0, verbose_name='Amount'),
        ),
    ]
