# Generated by Django 4.1.6 on 2024-11-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0119_alter_unregisteredgiftcard_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
