# Generated by Django 4.1.6 on 2024-11-24 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0120_transactions_is_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='sender_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
