# Generated by Django 4.1.6 on 2024-11-26 11:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0119_order_is_group_order'),
        ('billing', '0121_transactions_sender_name'),
    ]

    operations = [
    ]
