# Generated by Django 4.1.6 on 2024-12-17 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0122_merge_20241126_0301'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('not_applicable', 'Not_Applicable'), ('in_process', 'In_Process'), ('completed', 'Completed')], default='not_applicable', max_length=20, verbose_name='Refund Status'),
        ),
    ]
