# Generated by Django 4.1.6 on 2024-12-21 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0124_remove_order_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email'),
        ),
    ]
