# Generated by Django 4.1.6 on 2025-01-06 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0125_order_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='refund_status',
            field=models.CharField(choices=[('applicable', 'Applicable'), ('requested', 'Requested'), ('approved', 'Approved'), ('not_applicable', 'Not_Applicable'), ('in_process', 'In_Process'), ('refunded', 'Refunded'), ('declined', 'Declined')], default='applicable', max_length=20, verbose_name='Refund Status'),
        ),
    ]
