# Generated by Django 4.1.6 on 2025-02-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0126_order_refund_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='driver_info',
            field=models.JSONField(blank=True, default=dict, verbose_name='Driver Info'),
        ),
    ]
