# Generated by Django 4.2.19 on 2025-03-18 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0083_alter_fissionprize_prize_name'),
        ('billing', '0128_alter_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bxgy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.bxgy', verbose_name='BxGy'),
        ),
        migrations.AddField(
            model_name='order',
            name='bxgy_discount',
            field=models.FloatField(default=0, verbose_name='bxgy discount, '),
        ),
    ]
