# Generated by Django 4.2.19 on 2025-03-19 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0129_order_bxgy_order_bxgy_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bxgy',
        ),
        migrations.RemoveField(
            model_name='order',
            name='bxgy_discount',
        ),
    ]
