# Generated by Django 4.2.19 on 2025-03-19 05:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0085_bxgy_free_items_bxgy_items'),
        ('billing', '0130_remove_order_bxgy_remove_order_bxgy_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bxgy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.bxgy', verbose_name='BxGy'),
        ),
        migrations.AddField(
            model_name='order',
            name='bxgy_discount',
            field=models.FloatField(default=0, verbose_name='bxgy discount, '),
        ),
    ]
