# Generated by Django 4.2.19 on 2025-03-21 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0131_order_bxgy_order_bxgy_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bxgy_discount',
        ),
    ]
