# Generated by Django 4.2.19 on 2025-03-20 03:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0128_merge_20250211_0424'),
        ('billing', '0131_order_bxgy_order_bxgy_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='PayoutHistoryForHungry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('statement_start_date', models.DateTimeField(blank=True, null=True)),
                ('statement_end_date', models.DateTimeField(blank=True, null=True)),
                ('payout_amount', models.FloatField(default=0)),
                ('net_revenue', models.FloatField(default=0)),
                ('gross_revenue', models.FloatField(default=0)),
                ('delivery_fees', models.FloatField(default=0)),
                ('bag_fees', models.FloatField(default=0)),
                ('tips', models.FloatField(default=0)),
                ('utensil_fees', models.FloatField(default=0)),
                ('promotional_expenses', models.FloatField(default=0)),
                ('stripe_fees', models.FloatField(default=0)),
                ('service_fees_paid_to_chatchef', models.FloatField(default=0)),
                ('service_fees_paid_by_customer_to_restaurant', models.FloatField(default=0)),
                ('delivery_fees_bare_by_restaurant', models.FloatField(default=0)),
                ('tax_paid_by_customer', models.FloatField(default=0)),
                ('tax_paid_by_restaurant', models.FloatField(default=0)),
                ('invoice', models.FileField(upload_to='invoice/xls/%Y/%m/%d/')),
                ('pdf', models.FileField(upload_to='invoice/pdf/%Y/%m/%d/')),
                ('is_paid', models.BooleanField(default=False)),
                ('is_mailed', models.BooleanField(default=False)),
                ('adjustments', models.FloatField(default=0)),
                ('adjustments_note', models.TextField(blank=True, null=True)),
                ('uid', models.CharField(blank=True, max_length=255, null=True)),
                ('original_delivery_fees', models.FloatField(default=0)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.location')),
                ('orders', models.ManyToManyField(to='billing.order')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
