# Generated by Django 4.2.19 on 2025-03-21 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0132_remove_order_bxgy_discount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bxgy_discount',
            field=models.FloatField(default=0, verbose_name='bxgy discount, '),
        ),
    ]
