# Generated by Django 4.2.19 on 2025-03-21 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0132_payouthistoryforhungry'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payouthistoryforhungry',
            old_name='delivery_fees_bare_by_restaurant',
            new_name='amount_to_restaurant',
        ),
        migrations.RenameField(
            model_name='payouthistoryforhungry',
            old_name='promotional_expenses',
            new_name='bogo_discount',
        ),
        migrations.RenameField(
            model_name='payouthistoryforhungry',
            old_name='service_fees_paid_by_customer_to_restaurant',
            new_name='commission_amount',
        ),
        migrations.RenameField(
            model_name='payouthistoryforhungry',
            old_name='service_fees_paid_to_chatchef',
            new_name='commission_percentage',
        ),
        migrations.RenameField(
            model_name='payouthistoryforhungry',
            old_name='stripe_fees',
            new_name='container_fees',
        ),
        migrations.RenameField(
            model_name='payouthistoryforhungry',
            old_name='tax_paid_by_customer',
            new_name='customer_absorbed_delivery_fees',
        ),
        migrations.RenameField(
            model_name='payouthistoryforhungry',
            old_name='tax_paid_by_restaurant',
            new_name='delivery_fees_expense',
        ),
        migrations.RenameField(
            model_name='payouthistoryforhungry',
            old_name='tips',
            new_name='discount',
        ),
        migrations.RenameField(
            model_name='payouthistoryforhungry',
            old_name='utensil_fees',
            new_name='ht_profit',
        ),
        migrations.AddField(
            model_name='payouthistoryforhungry',
            name='restaurant_discount',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistoryforhungry',
            name='selling_price_inclusive_of_tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistoryforhungry',
            name='service_fee_to_hungrytiger',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistoryforhungry',
            name='service_fee_to_restaurant',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistoryforhungry',
            name='tax',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='payouthistoryforhungry',
            name='tips_for_restaurant',
            field=models.FloatField(default=0),
        ),
    ]
