# Generated by Django 4.2.19 on 2025-04-08 03:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0128_merge_20250211_0424'),
        ('billing', '0133_rename_delivery_fees_bare_by_restaurant_payouthistoryforhungry_amount_to_restaurant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantContract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commission_percentage', models.DecimalField(decimal_places=2, help_text='HungryTiger commission percentage', max_digits=5)),
                ('bogo_bear_by_restaurant', models.DecimalField(decimal_places=2, help_text='BOGO discount percentage borne by restaurant', max_digits=5)),
                ('restaurant_discount_percentage', models.DecimalField(decimal_places=2, help_text='Discount percentage offered by the restaurant', max_digits=5)),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='restaurantContact', to='food.restaurant', verbose_name='Restaurant')),
            ],
        ),
    ]
