# Generated by Django 4.2.19 on 2025-03-21 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0133_order_bxgy_discount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bxgy_discount',
        ),
    ]
