# Generated by Django 4.2.19 on 2025-04-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0135_order_actual_discount_order_actual_item_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ht_delivery_fee_expense',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='HT Delivery Fee Expense'),
        ),
    ]
