# Generated by Django 4.2.19 on 2025-04-15 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0135_order_bxgy_discount'),
        ('billing', '0137_remove_order_actual_discount_and_more'),
    ]

    operations = [
    ]
