# Generated by Django 4.2.19 on 2025-04-21 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0138_merge_20250414_0134'),
        ('billing', '0138_merge_20250415_1022'),
    ]

    operations = [
    ]
