# Generated by Django 4.2.19 on 2025-04-21 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0139_merge_20250420_0916'),
        ('billing', '0139_merge_20250421_0453'),
    ]

    operations = [
    ]
