# Generated by Django 4.2.19 on 2025-04-18 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0139_merge_20250418_0837'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='discount_hungrytiger',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='HungryTiger Discount'),
        ),
    ]
