# Generated by Django 4.2.19 on 2025-04-27 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0140_merge_20250421_0938'),
        ('billing', '0140_order_discount_hungrytiger'),
    ]

    operations = [
    ]
