# Generated by Django 4.2.19 on 2025-04-25 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0141_merge_20250425_0612'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_discount_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Restaurant Discount Percentage at Order Time'),
        ),
    ]
