# Generated by Django 4.2.19 on 2025-04-27 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0141_merge_20250427_0018'),
        ('billing', '0142_order_restaurant_discount_percentage'),
    ]

    operations = [
    ]
