# Generated by Django 4.2.19 on 2025-04-27 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0143_merge_20250427_0201'),
        ('billing', '0143_merge_20250427_0204'),
    ]

    operations = [
    ]
