# Generated by Django 4.2.19 on 2025-05-01 15:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0037_localdeal'),
        ('billing', '0145_merge_20250428_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_local_deal_redeemed',
            field=models.BooleanField(default=False, verbose_name='Is Local Deal Redeemed'),
        ),
        migrations.AddField(
            model_name='order',
            name='local_deal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reward.localdeal', verbose_name='Local Deal'),
        ),
        migrations.AddField(
            model_name='order',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qr_codes/%Y/%m/%d/', verbose_name='QR Code'),
        ),
        migrations.AddField(
            model_name='order',
            name='redeemed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Redeemed At'),
        ),
        migrations.AlterField(
            model_name='order',
            name='order_method',
            field=models.CharField(choices=[('delivery', 'DELIVERY'), ('restaurant_delivery', 'RESTAURANT_DELIVERY'), ('pickup', 'PICKUP'), ('dine_in', 'DINE_IN'), ('local_deal', 'LOCAL_DEAL')], default='delivery', max_length=20, verbose_name='Order method'),
        ),
    ]
