# Generated by Django 4.2.19 on 2025-05-04 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0146_order_is_local_deal_redeemed_order_local_deal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='restaurant_accepted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Restaurant Accepted Time'),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_accepted_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rider Accepted Time'),
        ),
        migrations.AddField(
            model_name='order',
            name='rider_pickup_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Rider Pickup Time'),
        ),
    ]
