# Generated by Django 4.2.19 on 2025-05-05 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0147_order_restaurant_accepted_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='solid_voucher_code',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Solid Voucher Code'),
        ),
    ]
