# Generated by Django 4.2.19 on 2025-05-05 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0148_order_solid_voucher_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_man',
            field=models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='Delivery Man'),
        ),
    ]
