# Generated by Django 4.2.19 on 2025-05-05 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0149_order_delivery_man'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_received_cash',
            field=models.BooleanField(default=False, verbose_name='Admin Received Cash'),
        ),
    ]
