# Generated by Django 4.2.19 on 2025-05-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0151_alter_order_admin_received_cash'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='admin_received_cash',
            new_name='admin_received_cash_temp',
        ),
    ]
