# Generated by Django 4.2.19 on 2025-05-06 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0152_rename_admin_received_cash_order_admin_received_cash_temp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin_received_cash_temp',
        ),
    ]
