# Generated by Django 4.2.19 on 2025-05-06 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0153_remove_order_admin_received_cash_temp'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_received_cash',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Admin Received Cash'),
        ),
    ]
