# Generated by Django 4.2.19 on 2025-05-06 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0154_order_admin_received_cash'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='lucky_flip_gift',
            field=models.JSONField(blank=True, default=dict, help_text='Optional lucky-flip gift details, including name and price.', null=True, verbose_name='Lucky Flip Gift'),
        ),
    ]
