# Generated by Django 4.2.19 on 2025-05-07 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0155_order_lucky_flip_gift'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcontract',
            name='ht_voucher_percentage_borne_by_restaurant',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='HT Voucher percentage borne by Restaurant', max_digits=5),
        ),
    ]
