# Generated by Django 4.2.19 on 2025-05-07 03:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0156_restaurantcontract_ht_voucher_percentage_borne_by_restaurant'),
    ]

    operations = [
    ]
