# Generated by Django 4.2.19 on 2025-05-07 03:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0158_change_admin_cash_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='admin_received_cash',
        ),
    ]
