# Generated by Django 4.2.19 on 2025-05-22 05:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0160_order_admin_received_cash'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='bxgy',
        ),
    ]
