# Generated by Django 4.2.19 on 2025-05-22 05:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0097_bxgy_free_items'),
        ('billing', '0161_remove_order_bxgy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='bxgy',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.bxgy', verbose_name='BxGy'),
        ),
    ]
