# Generated by Django 4.2.19 on 2025-05-25 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0042_alter_reward_restaurant_alter_rewardgroup_company_and_more'),
        ('billing', '0162_order_bxgy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='local_deal',
        ),
        migrations.AddField(
            model_name='order',
            name='local_deals',
            field=models.ManyToManyField(blank=True, to='reward.localdeal', verbose_name='Local Deals'),
        ),
    ]
