# Generated by Django 4.2.19 on 2025-05-24 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0162_order_bxgy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_amount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Commission Amount'),
        ),
        migrations.AddField(
            model_name='order',
            name='commission_percentage',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Commission Percentage'),
        ),
        migrations.AddField(
            model_name='order',
            name='restaurant_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Restaurant Discount'),
        ),
    ]
