# Generated by Django 4.2.19 on 2025-05-25 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0163_remove_order_local_deal_order_local_deals'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='local_deals',
            new_name='local_deal',
        ),
    ]
