# Generated by Django 4.2.19 on 2025-05-25 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0165_remove_order_local_deal_order_qr_code_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='qr_code_value',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='QR Code Value'),
        ),
    ]
