# Generated by Django 4.2.19 on 2025-05-25 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0166_alter_order_qr_code_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='qr_code_value',
        ),
    ]
