# Generated by Django 4.2.19 on 2025-05-25 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0169_order_local_deal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='local_deal',
        ),
    ]
