# Generated by Django 4.2.19 on 2025-05-25 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0042_alter_reward_restaurant_alter_rewardgroup_company_and_more'),
        ('billing', '0170_remove_order_local_deal'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='local_deal',
            field=models.ManyToManyField(blank=True, to='reward.localdeal', verbose_name='Local Deal'),
        ),
    ]
