# Generated by Django 4.2.19 on 2025-05-25 08:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0163_order_commission_amount_order_commission_percentage_and_more'),
        ('billing', '0171_order_local_deal'),
    ]

    operations = [
    ]
