# Generated by Django 4.2.19 on 2025-06-01 04:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0172_merge_20250525_0156'),
        ('billing', '0173_order_receive_date_ht'),
    ]

    operations = [
    ]
