# Generated by Django 4.2.19 on 2025-06-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0174_merge_20250601_2300'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='prep_time',
            field=models.IntegerField(default=30, verbose_name='Prep time'),
        ),
    ]
