# Generated by Django 4.2.19 on 2025-06-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0174_merge_20250602_1714'),
        ('billing', '0175_alter_order_prep_time'),
    ]

    operations = [
    ]
