# Generated by Django 4.2.19 on 2025-06-22 09:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0177_merge_20250618_1440"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="on_time_guarantee_fee",
            field=models.FloatField(default=6),
        ),
        migrations.AddField(
            model_name="order",
            name="on_time_guarantee_opted_in",
            field=models.BooleanField(default=False),
        ),
    ]
