# Generated by Django 4.2.19 on 2025-06-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0177_merge_20250618_0312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='special_discount',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Special Discount'),
        ),
        migrations.AddField(
            model_name='order',
            name='special_discount_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Special Discount Reason'),
        ),
        migrations.AlterField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
    ]
