# Generated by Django 4.2.19 on 2025-06-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0178_order_special_discount_order_special_discount_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantcontract',
            name='restaurant_accepted_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Discount percentage accepted by the restaurant', max_digits=5),
        ),
        migrations.AddField(
            model_name='restaurantcontract',
            name='restaurant_voucher_codes',
            field=models.JSONField(blank=True, help_text='List of voucher codes accepted by the restaurant', null=True),
        ),
    ]
