# Generated by Django 4.2.19 on 2025-06-22 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0178_order_on_time_guarantee_fee_and_more"),
        (
            "billing",
            "0178_order_special_discount_order_special_discount_reason_and_more",
        ),
    ]

    operations = []
