# Generated by Django 4.2.19 on 2025-06-30 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0179_merge_20250623_0215"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="auto_apply_on_time_reward",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="order",
            name="used_on_time_reward",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
