# Generated by Django 4.2.19 on 2025-07-07 06:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("billing", "0179_restaurantcontract_restaurant_accepted_discount_and_more"),
        ("billing", "0180_order_auto_apply_on_time_reward_and_more"),
    ]

    operations = []
