# Generated by Django 4.1.6 on 2024-04-18 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_theme', '0002_alter_theme_background_color_alter_theme_cart_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='is_active'),
        ),
    ]
