# Generated by Django 4.1.6 on 2024-08-01 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dynamic_theme', '0003_theme_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='theme',
            name='cart_color',
        ),
        migrations.AddField(
            model_name='theme',
            name='button_bg_color',
            field=models.CharField(blank=True, default='red', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='button_hover_bg_color',
            field=models.CharField(blank=True, default='#F7DDA0', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='button_hover_text_color',
            field=models.CharField(blank=True, default='#000', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='button_text_color',
            field=models.CharField(blank=True, default='#fff', max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='theme',
            name='card_color',
            field=models.CharField(blank=True, default='#fff', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='background_color',
            field=models.CharField(blank=True, default='#e8e8e8', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='danger_color',
            field=models.CharField(blank=True, default='red', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='disable_color',
            field=models.CharField(blank=True, default='gray', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='positive_color',
            field=models.CharField(blank=True, default='green', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='primary_color',
            field=models.CharField(blank=True, default='pink', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='secondary_color',
            field=models.CharField(blank=True, default='#F7DDA0', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='stock_color',
            field=models.CharField(blank=True, default='#fff', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='text_color',
            field=models.CharField(blank=True, default='#000', max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='warning_color',
            field=models.CharField(blank=True, default='yellow', max_length=150, null=True),
        ),
    ]
