# Generated by Django 4.1.6 on 2023-06-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExtraData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='Label')),
                ('value', models.TextField(blank=True, verbose_name='Value')),
                ('extra', models.JSONField(default=dict, verbose_name='Extra')),
            ],
            options={
                'verbose_name': 'Extra Data',
                'verbose_name_plural': 'Extra Data',
            },
        ),
    ]
