# Generated by Django 4.1.6 on 2024-04-29 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppStore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('version', models.FloatField(default=0, verbose_name='App Version')),
                ('files', models.FileField(upload_to='apps', verbose_name='file')),
                ('type', models.CharField(choices=[('oms', 'OMS'), ('do', 'DO')], default='oms', max_length=30, verbose_name='apps type')),
            ],
            options={
                'verbose_name': 'App Store',
                'ordering': ['-id'],
            },
        ),
    ]
