# Generated by Django 4.1.6 on 2024-07-26 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0093_restaurant_payment_methods_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisitorAnalytics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('source', models.CharField(choices=[('facebook', 'FACEBOOK'), ('whats_app', 'WHATS_APP'), ('table', 'TABLE'), ('banner', 'BANNER'), ('business_card', 'BUSINESS_CARD'), ('poster', 'POSTER'), ('flyer', 'FLYER'), ('coupon', 'COUPON'), ('na', 'NA')], default='na', max_length=50, verbose_name='source')),
                ('count', models.CharField(choices=[('do', 'DO'), ('cart', 'CART'), ('order_confirm', 'ORDER_CONFIRM'), ('payment_confirm', 'PAYMENT_CONFIRM')], default='do', max_length=50, verbose_name='count')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='restaurant')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
