# Generated by Django 4.1.6 on 2024-09-18 06:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitoranalytics',
            name='source',
            field=models.CharField(choices=[('facebook', 'FACEBOOK'), ('whats_app', 'WHATS_APP'), ('instagram', 'INSTAGRAM'), ('google', 'GOOGLE'), ('table', 'TABLE'), ('banner', 'BANNER'), ('business_card', 'BUSINESS_CARD'), ('poster', 'POSTER'), ('flyer', 'FLYER'), ('coupon', 'COUPON'), ('na', 'NA')], default='na', max_length=50, verbose_name='source'),
        ),
    ]
