# Generated by Django 4.1.6 on 2023-12-18 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Action_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('action', models.CharField(blank=True, max_length=255, null=True, verbose_name='action')),
                ('logs', models.TextField(blank=True, null=True, verbose_name='logs')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.location', verbose_name='location')),
                ('restaurant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='restaurant')),
            ],
            options={
                'verbose_name': 'Action Log',
                'verbose_name_plural': 'Action Logs',
                'ordering': ['-id'],
            },
        ),
    ]
