# Generated by Django 4.2.19 on 2025-03-10 00:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0128_merge_20250211_0424'),
        ('accounts', '0036_user_referred_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='TokenFCM',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=255, unique=True)),
                ('device_type', models.CharField(choices=[('web', 'Web'), ('ios', 'iOS')], default='web', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=150, verbose_name='Key')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Title')),
                ('notification_title', models.CharField(max_length=250, verbose_name='Notification Title')),
                ('notification_body', models.TextField(blank=True, verbose_name='Notification body')),
                ('click_action', models.CharField(blank=True, max_length=200, verbose_name='Click Action')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='Data')),
                ('notification_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.image', verbose_name='Notification Image')),
            ],
            options={
                'verbose_name': 'Push Template',
                'verbose_name_plural': 'Push Templates',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FirebasePushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='Device ID')),
                ('platform', models.CharField(choices=[('web', 'WEB'), ('android', 'ANDROID'), ('ios', 'IOS')], default='web', max_length=15, verbose_name='Platform')),
                ('push_token', models.TextField(blank=True, verbose_name='Push token')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Firebase Push Token',
                'verbose_name_plural': 'Firebase Push Tokens',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='CompanyPushToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('device_id', models.CharField(blank=True, max_length=100, verbose_name='Device ID')),
                ('platform', models.CharField(choices=[('web', 'WEB'), ('android', 'ANDROID'), ('ios', 'IOS')], default='web', max_length=15, verbose_name='Platform')),
                ('push_token', models.TextField(blank=True, verbose_name='Push token')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Company')),
            ],
            options={
                'verbose_name': 'Company Push Token',
                'verbose_name_plural': 'Company Push Tokens',
                'ordering': ['-id'],
            },
        ),
    ]
