# Generated by Django 4.2.19 on 2025-03-13 05:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0128_merge_20250211_0424'),
        ('firebase', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromotionalCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_percentage', models.PositiveIntegerField()),
                ('campaign_name', models.CharField(max_length=255, verbose_name='Promotion Name')),
                ('dish_name', models.CharField(max_length=255, verbose_name='Dish Name')),
                ('campaign_image', models.ImageField(blank=True, null=True, upload_to='promotional_campaign_images/', verbose_name='Image')),
                ('campaign_start_time', models.DateTimeField(verbose_name='Start Date')),
                ('campaign_end_time', models.DateTimeField(verbose_name='End Date')),
                ('schedule_times', models.JSONField(default=list, verbose_name='Schedule Times')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotional_campaigns', to='food.restaurant')),
            ],
        ),
    ]
