# Generated by Django 4.2.19 on 2025-03-15 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0002_promotionalcampaign'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionalcampaign',
            name='campaign_end_time',
        ),
        migrations.RemoveField(
            model_name='promotionalcampaign',
            name='campaign_start_time',
        ),
        migrations.AddField(
            model_name='promotionalcampaign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Active'),
        ),
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='schedule_times',
            field=models.JSONField(default=dict, verbose_name='Schedule Times'),
        ),
    ]
