# Generated by Django 4.2.19 on 2025-03-16 08:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0128_merge_20250211_0424'),
        ('firebase', '0003_remove_promotionalcampaign_campaign_end_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promotionalcampaign',
            name='campaign_name',
        ),
        migrations.RemoveField(
            model_name='promotionalcampaign',
            name='discount_percentage',
        ),
        migrations.RemoveField(
            model_name='promotionalcampaign',
            name='dish_name',
        ),
        migrations.AddField(
            model_name='promotionalcampaign',
            name='category',
            field=models.CharField(choices=[('BOGO', 'Buy One Get One'), ('FIRST_ORDER_DISCOUNT', 'First Order Discount'), ('PERCENTAGE_DISCOUNT', 'Percentage Discount'), ('CASHBACK', 'Cashback Offer'), ('FREE_DELIVERY', 'Free Delivery'), ('FLASH_SALE', 'Flash Sale'), ('LIMITED_TIME_OFFER', 'Limited Time Offer'), ('HOLIDAY_SPECIAL', 'Holiday Special')], default='GENERAL', max_length=50, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='promotionalcampaign',
            name='message',
            field=models.TextField(default='No message here', verbose_name='Message/Body'),
        ),
        migrations.AddField(
            model_name='promotionalcampaign',
            name='title',
            field=models.CharField(default='No Title here', max_length=255, verbose_name='Title'),
        ),
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='promotional_campaigns', to='food.restaurant', verbose_name='Restaurant'),
        ),
    ]
