# Generated by Django 4.2.19 on 2025-03-17 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0004_remove_promotionalcampaign_campaign_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='message',
            field=models.TextField(verbose_name='Message/Body'),
        ),
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Title'),
        ),
    ]
