# Generated by Django 4.2.19 on 2025-03-17 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0005_alter_promotionalcampaign_message_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TokenFCM',
        ),
    ]
