# Generated by Django 4.2.19 on 2025-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firebase', '0007_tokenfcm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotionalcampaign',
            name='category',
            field=models.CharField(choices=[('BOGO', 'Buy One Get One'), ('BXGY', 'Buy X Get Y'), ('FIRST_ORDER_DISCOUNT', 'First Order Discount'), ('PERCENTAGE_DISCOUNT', 'Percentage Discount'), ('CASHBACK', 'Cashback Offer'), ('FREE_DELIVERY', 'Free Delivery'), ('FLASH_SALE', 'Flash Sale'), ('LIMITED_TIME_OFFER', 'Limited Time Offer'), ('HOLIDAY_SPECIAL', 'Holiday Special')], default='GENERAL', max_length=50, verbose_name='Category'),
        ),
    ]
