# Generated by Django 4.1.6 on 2023-10-04 20:01

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0009_user_address'),
        ('food', '0045_merge_20231004_0411'),
    ]

    operations = [
        migrations.CreateModel(
            name='Duration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Start Date')),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='End Date')),
            ],
            options={
                'verbose_name': 'Duration',
                'verbose_name_plural': 'Durations',
            },
        ),
        migrations.CreateModel(
            name='SpendXSaveYPromoOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('min_spend', models.FloatField(default=0, verbose_name='Min spend')),
                ('save_amount', models.FloatField(default=0, verbose_name='Save amount')),
            ],
            options={
                'verbose_name': 'Spend X Save Y Promotion Option',
                'verbose_name_plural': 'Spend X Save Y Promotion Options',
            },
        ),
        migrations.CreateModel(
            name='SpendXSaveY',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Promotion name')),
                ('audience', models.CharField(choices=[('all', 'ALL'), ('members', 'MEMBERS')], default='all', max_length=20, verbose_name='Audience')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company')),
                ('durations', models.ManyToManyField(blank=True, to='marketing.duration', verbose_name='Durations')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location')),
                ('promo_option', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.spendxsaveypromooption', verbose_name='Promo option')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Spend X Save Y',
                'verbose_name_plural': 'Spend X Save Y Campaigns',
            },
        ),
    ]
