# Generated by Django 4.1.6 on 2023-10-09 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0047_alter_category_menu'),
        ('accounts', '0009_user_address'),
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('amount', models.FloatField(default=0, verbose_name='Amount')),
                ('minimum_spend', models.FloatField(default=0, verbose_name='Minimum Spend')),
                ('max_redeem_value', models.FloatField(blank=True, null=True, verbose_name='Maximum Redeem Value')),
                ('audience', models.CharField(choices=[('all', 'ALL'), ('members', 'MEMBERS')], default='all', max_length=20, verbose_name='Audience')),
                ('voucher_code', models.CharField(max_length=50, verbose_name='Voucher Code')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company')),
                ('durations', models.ManyToManyField(blank=True, to='marketing.duration', verbose_name='Durations')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Voucher',
                'verbose_name_plural': 'Vouchers',
            },
        ),
    ]
