# Generated by Django 4.1.6 on 2023-10-16 21:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_activationcampaign_remove_spendxsavey_audience_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPromotionOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('people', models.IntegerField(default=2, verbose_name='People')),
                ('discount', models.IntegerField(default=0, verbose_name='Discount')),
            ],
            options={
                'verbose_name': 'Group Promotion Option',
                'verbose_name_plural': 'Group Promotion Options',
            },
        ),
        migrations.CreateModel(
            name='GroupPromotion',
            fields=[
                ('activationcampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing.activationcampaign')),
                ('promo_options', models.ManyToManyField(to='marketing.grouppromotionoption', verbose_name='Promo Options')),
            ],
            options={
                'verbose_name': 'Group Promotion',
                'verbose_name_plural': 'Group Promotions',
            },
            bases=('marketing.activationcampaign',),
        ),
    ]
