# Generated by Django 4.1.6 on 2023-10-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_grouppromotionoption_grouppromotion'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoyaltyProgram',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('is_enabled', models.BooleanField(default=True, verbose_name='Is enabled')),
                ('validity_days', models.IntegerField(default=1, verbose_name='Validity Days')),
                ('covers_delivery_fees', models.BooleanField(default=False, verbose_name='Covers Delivery')),
                ('reward_type', models.CharField(choices=[('discount', 'DISCOUNT'), ('free_meal', 'FREE_MEAL')], default='discount', max_length=15, verbose_name='Reward type')),
                ('min_orders', models.IntegerField(default=0, verbose_name='Minimum Orders')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='company')),
                ('location', models.ManyToManyField(blank=True, null=True, to='food.location', verbose_name='Location')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Loyalty Program',
                'verbose_name_plural': 'Loyalty Programs',
            },
        ),
    ]
