# Generated by Django 4.1.6 on 2023-10-30 21:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_user_reward_points'),
        ('food', '0053_alter_timetable_opening_hour'),
        ('marketing', '0005_loyaltyprogram'),
    ]

    operations = [
        migrations.CreateModel(
            name='FissionPrize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('prize_name', models.CharField(max_length=250, verbose_name='prize name')),
                ('amount', models.FloatField(blank=True, null=True, verbose_name='amount')),
                ('probability', models.FloatField(verbose_name='probability')),
            ],
            options={
                'verbose_name': 'Fission Prize',
                'verbose_name_plural': 'Fission Prizes',
            },
        ),
        migrations.CreateModel(
            name='FissionCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company')),
                ('prizes', models.ManyToManyField(blank=True, to='marketing.fissionprize', verbose_name='Fission prizes')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Fission Campaign',
                'verbose_name_plural': 'Fission Campaigns',
            },
        ),
    ]
