# Generated by Django 4.1.6 on 2023-11-06 21:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_user_reward_points'),
        ('food', '0053_alter_timetable_opening_hour'),
        ('marketing', '0006_fissionprize_fissioncampaign'),
    ]

    operations = [
        migrations.CreateModel(
            name='BirthdayGift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('membership_only', models.BooleanField(default=False, verbose_name='Membership Only')),
                ('has_condition', models.BooleanField(default=False, verbose_name='Has condition')),
                ('minimum_spent', models.IntegerField(default=0, verbose_name='Minimum Spent')),
                ('gift_option_type', models.CharField(choices=[('SpendXSaveY', 'SpendXSaveY'), ('Voucher', 'Voucher'), ('Bogo', 'Bogo'), ('GroupOrdering', 'GroupOrdering')], default='SpendXSaveY', max_length=20, verbose_name='Gift Option Type')),
                ('object_id', models.PositiveIntegerField()),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='company')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('location', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location')),
                ('received_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('restaurant', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Birthday Gift',
                'verbose_name_plural': 'Birthday gifts',
            },
        ),
    ]
