# Generated by Django 4.1.6 on 2023-11-14 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0057_alter_modifiergroup_menu'),
        ('marketing', '0007_birthdaygift'),
    ]

    operations = [
        migrations.AlterField(
            model_name='birthdaygift',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='birthdaygift',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant'),
        ),
    ]
