# Generated by Django 4.1.6 on 2023-11-14 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0008_alter_birthdaygift_location_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fissionprize',
            name='prize_name',
            field=models.CharField(choices=[('bogo', 'BOGO'), ('percentage', 'PERCENTAGE'), ('fixed', 'FIXED')], default='percentage', max_length=250, verbose_name='prize name'),
        ),
    ]
