# Generated by Django 4.1.6 on 2023-11-15 19:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_restaurantuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0057_alter_modifiergroup_menu'),
        ('marketing', '0009_alter_fissionprize_prize_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('allow_custom', models.BooleanField(default=False, verbose_name='Allow custom')),
                ('amounts', models.JSONField(default=list, verbose_name='Amounts')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='company')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location')),
                ('received_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Gift Card',
                'verbose_name_plural': 'Gift Cards',
            },
        ),
    ]
