# Generated by Django 4.1.6 on 2023-11-16 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0010_giftcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='birthdaygift',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is active'),
        ),
    ]
