# Generated by Django 4.1.6 on 2023-11-16 20:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0057_alter_modifiergroup_menu'),
        ('accounts', '0011_restaurantuser'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0011_birthdaygift_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loyaltyprogram',
            name='location',
            field=models.ManyToManyField(blank=True, to='food.location', verbose_name='Location'),
        ),
        migrations.CreateModel(
            name='MembershipCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Is active')),
                ('name', models.CharField(max_length=250, verbose_name='Name')),
                ('duration', models.PositiveIntegerField(default=1, verbose_name='Duration')),
                ('price', models.FloatField(verbose_name='Price')),
                ('anytime', models.BooleanField(default=False, verbose_name='Anytime')),
                ('discount', models.FloatField(default=0, verbose_name='Discount')),
                ('limit_per_month', models.PositiveIntegerField(default=0, verbose_name='Limit per month')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='company')),
                ('dishes', models.ManyToManyField(blank=True, to='food.menuitem', verbose_name='Dishes')),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location')),
                ('received_by', models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='User')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant')),
                ('usage_time', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.duration', verbose_name='Usage time')),
            ],
            options={
                'verbose_name': 'Membership Card',
                'verbose_name_plural': 'Membership Cards',
            },
        ),
    ]
