# Generated by Django 4.1.6 on 2023-11-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0012_alter_loyaltyprogram_location_membershipcard'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissioncampaign',
            name='availability',
            field=models.CharField(choices=[('after_every_order', 'AFTER_EVERY_ORDER'), ('once_every_user', 'ONCE_EVERY_USER'), ('after_sign_up', 'AFTER_SIGN_UP')], default='after_every_order', max_length=25, verbose_name='Availability'),
        ),
        migrations.AlterField(
            model_name='birthdaygift',
            name='gift_option_type',
            field=models.CharField(choices=[('SpendXSaveY', 'SpendXSaveY'), ('Voucher', 'Voucher'), ('Bogo', 'Bogo'), ('GroupPromotion', 'GroupPromotion')], default='SpendXSaveY', max_length=20, verbose_name='Gift Option Type'),
        ),
    ]
