# Generated by Django 4.1.6 on 2023-11-28 16:29

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0015_userreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissioncampaign',
            name='color',
            field=models.CharField(blank=True, max_length=15, verbose_name='Color'),
        ),
        migrations.CreateModel(
            name='RatingAndReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('rating', models.IntegerField()),
                ('review', models.TextField()),
                ('menuItem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='food.menuitem', verbose_name='menu items')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='customer')),
            ],
            options={
                'verbose_name': 'Rating and Review',
                'verbose_name_plural': 'Ratings and Reviews',
                'ordering': ['-id'],
            },
        ),
    ]
