# Generated by Django 4.1.6 on 2023-12-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_fissioncampaign_color_ratingandreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='ratingandreview',
            name='is_approved',
            field=models.BooleanField(default=False, verbose_name='is approved'),
        ),
    ]
