# Generated by Django 4.1.6 on 2023-12-06 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0016_fissioncampaign_color_ratingandreview'),
    ]

    operations = [
        migrations.AddField(
            model_name='loyaltyprogram',
            name='discount_amount',
            field=models.FloatField(default=1, verbose_name='Discount amount'),
        ),
    ]
