# Generated by Django 4.1.6 on 2023-12-13 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_loyaltyprogram_discount_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membershipcard',
            name='usage_time',
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='end_time',
            field=models.TimeField(blank=True, null=True, verbose_name='End time'),
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='start_time',
            field=models.TimeField(blank=True, null=True, verbose_name='Start time'),
        ),
    ]
