# Generated by Django 4.1.6 on 2023-12-06 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0020_remove_rating_user_rating_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='menu items'),
        ),
        migrations.DeleteModel(
            name='Review',
        ),
    ]
