# Generated by Django 4.1.6 on 2023-12-06 06:14

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0021_rating_review_delete_review'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('menuItem', 'user')},
        ),
    ]
