# Generated by Django 4.1.6 on 2023-12-07 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0017_loyaltyprogram_discount_amount'),
        ('marketing', '0023_alter_rating_unique_together_review_and_more'),
    ]

    operations = [
    ]
