# Generated by Django 4.1.6 on 2023-12-14 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0018_remove_membershipcard_usage_time_and_more'),
        ('marketing', '0024_merge_20231207_1422'),
    ]

    operations = [
    ]
