# Generated by Django 4.1.6 on 2023-12-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0025_merge_20231214_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissioncampaign',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Logo Image'),
        ),
    ]
