# Generated by Django 4.1.6 on 2023-12-14 20:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0026_fissioncampaign_logo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='fissioncampaign',
            options={'ordering': ['-id'], 'verbose_name': 'Fission Campaign', 'verbose_name_plural': 'Fission Campaigns'},
        ),
    ]
