# Generated by Django 4.1.6 on 2023-12-15 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_alter_additionalcondition_items_and_more'),
        ('marketing', '0027_alter_fissioncampaign_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissionprize',
            name='reward_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reward.rewardgroup', verbose_name='reward_group'),
        ),
    ]
