# Generated by Django 4.1.6 on 2023-12-15 21:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_alter_additionalcondition_items_and_more'),
        ('marketing', '0028_fissionprize_reward_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='reward_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reward.rewardgroup', verbose_name='Reward Group'),
        ),
    ]
