# Generated by Django 4.1.6 on 2023-12-16 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0029_userreward_reward_group'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserReward',
        ),
    ]
