# Generated by Django 4.1.6 on 2023-12-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
        ('marketing', '0030_delete_userreward'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host', models.CharField(max_length=255, verbose_name='email host')),
                ('email_port', models.PositiveIntegerField(verbose_name='email port')),
                ('email_use_tls', models.BooleanField(default=True, verbose_name='email use ssl')),
                ('email_host_user', models.EmailField(max_length=254, verbose_name='email host user')),
                ('email_host_password', models.CharField(max_length=255, verbose_name='email host password')),
                ('restaurant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
