# Generated by Django 4.1.6 on 2023-12-26 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0031_emailconfiguration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailconfiguration',
            name='email_use_tls',
            field=models.BooleanField(default=True, verbose_name='email use tls'),
        ),
    ]
