# Generated by Django 4.1.6 on 2024-01-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
        ('marketing', '0032_alter_emailconfiguration_email_use_tls'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('subject', models.CharField(max_length=255, verbose_name='subject')),
                ('message', models.CharField(blank=True, max_length=599, null=True, verbose_name='message')),
                ('html_content', models.CharField(blank=True, max_length=699, null=True, verbose_name='html_content')),
                ('scheduled_time', models.DateTimeField(blank=True, null=True, verbose_name='scheduled time')),
                ('sender_email', models.CharField(blank=True, max_length=255, verbose_name='sender email')),
                ('restaurant', models.ManyToManyField(to='food.restaurant', verbose_name='restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
