# Generated by Django 4.1.6 on 2024-01-04 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
        ('marketing', '0033_emailhistory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emailhistory',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='restaurant',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='food.restaurant'),
        ),
    ]
