# Generated by Django 4.1.6 on 2024-01-12 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0033_emailhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='spendxsavey',
            name='min_spend',
            field=models.FloatField(default=0, verbose_name='Min spend'),
        ),
        migrations.AddField(
            model_name='spendxsavey',
            name='save_amount',
            field=models.FloatField(default=0, verbose_name='Save amount'),
        ),
    ]
