# Generated by Django 4.1.6 on 2024-01-05 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0034_remove_emailhistory_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailhistory',
            name='audience',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='audience'),
        ),
        migrations.AddField(
            model_name='emailhistory',
            name='program',
            field=models.CharField(blank=True, max_length=599, null=True, verbose_name='program'),
        ),
    ]
