# Generated by Django 4.1.6 on 2024-01-15 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0034_spendxsavey_min_spend_spendxsavey_save_amount'),
        ('marketing', '0035_emailhistory_audience_emailhistory_program'),
    ]

    operations = [
    ]
