# Generated by Django 4.1.6 on 2024-02-28 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0063_location_is_location_closed'),
        ('marketing', '0036_merge_20240115_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.image', verbose_name='Image'),
        ),
    ]
