# Generated by Django 4.1.6 on 2024-03-18 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0037_voucher_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissioncampaign',
            name='durations',
            field=models.ManyToManyField(blank=True, to='marketing.duration', verbose_name='Durations'),
        ),
    ]
