# Generated by Django 4.1.6 on 2024-03-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0038_fissioncampaign_durations'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissioncampaign',
            name='background_color',
            field=models.CharField(blank=True, max_length=15, verbose_name='Background Color'),
        ),
        migrations.AddField(
            model_name='fissioncampaign',
            name='background_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Background Image'),
        ),
        migrations.AddField(
            model_name='fissioncampaign',
            name='max_flip_per_user',
            field=models.PositiveIntegerField(default=1, verbose_name='Max flip per user'),
        ),
        migrations.AddField(
            model_name='fissioncampaign',
            name='max_flip_period',
            field=models.CharField(default='weekly', max_length=20, verbose_name='Max flip period'),
        ),
        migrations.AddField(
            model_name='fissioncampaign',
            name='validity_type',
            field=models.CharField(choices=[('repeating', 'REPEATING'), ('time_limit', 'TIME_LIMIT')], default='time_limit', max_length=30, verbose_name='Validity Type'),
        ),
        migrations.AddField(
            model_name='fissioncampaign',
            name='weekdays',
            field=models.JSONField(default=list, verbose_name='Weekdays'),
        ),
    ]
