# Generated by Django 4.1.6 on 2024-03-23 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0039_fissioncampaign_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissioncampaign',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Is Enabled'),
        ),
    ]
