# Generated by Django 4.1.6 on 2024-04-02 17:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0040_fissioncampaign_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='fissioncampaign',
            name='last_used_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Last used flip'),
        ),
        migrations.AddField(
            model_name='fissioncampaign',
            name='last_week_users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Last week users'),
        ),
    ]
