# Generated by Django 4.1.6 on 2024-03-30 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0019_rename_reward_grp_rewardmanage_reward_group'),
        ('marketing', '0040_fissioncampaign_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='reward',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reward.reward'),
        ),
    ]
