# Generated by Django 4.1.6 on 2024-04-03 16:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0041_fissioncampaign_last_used_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fissioncampaign',
            name='last_week_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Last week users'),
        ),
    ]
