# Generated by Django 4.1.6 on 2024-04-04 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0041_voucher_reward'),
        ('marketing', '0042_alter_fissioncampaign_last_week_users'),
    ]

    operations = [
    ]
