# Generated by Django 4.1.6 on 2024-04-20 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0043_merge_20240404_1016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fissioncampaign',
            name='availability',
            field=models.CharField(choices=[('after_every_order', 'AFTER_EVERY_ORDER'), ('once_every_user', 'ONCE_EVERY_USER'), ('after_sign_up', 'AFTER_SIGN_UP'), ('after_joins_group', 'AFTER_JOINS_GROUP'), ('once_every_week', 'ONCE_EVERY_WEEK')], default='after_every_order', max_length=25, verbose_name='Availability'),
        ),
    ]
