# Generated by Django 4.1.6 on 2024-06-13 09:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0044_alter_fissioncampaign_availability'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpendXSaveYManager',
            fields=[
                ('activationcampaign_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing.activationcampaign')),
            ],
            options={
                'verbose_name': 'Spend X Save Y Manager',
                'verbose_name_plural': 'Spend X Save Y Managers',
            },
            bases=('marketing.activationcampaign',),
        ),
        migrations.RemoveField(
            model_name='spendxsavey',
            name='promo_option',
        ),
        migrations.AddField(
            model_name='spendxsavey',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.spendxsaveymanager', verbose_name='Manager'),
        ),
    ]
