# Generated by Django 4.1.6 on 2024-06-17 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0045_spendxsaveymanager_remove_spendxsavey_promo_option_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='available_to',
            field=models.CharField(choices=[('all', 'ALL'), ('members', 'MEMBERS'), ('first_order', 'FIRST_ORDER')], default='all', max_length=20, verbose_name='Audience'),
        ),
    ]
