# Generated by Django 4.1.6 on 2024-06-20 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0046_voucher_available_to'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='available_to',
            field=models.CharField(choices=[('all', 'ALL'), ('members', 'MEMBERS'), ('first_order', 'FIRST_ORDER')], default='all', max_length=20, verbose_name='Available To'),
        ),
    ]
