# Generated by Django 4.1.6 on 2024-08-08 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0048_contactusdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='bogo',
            name='is_disabled',
            field=models.BooleanField(default=False),
        ),
    ]
