# Generated by Django 4.1.6 on 2024-09-02 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0049_bogo_is_disabled'),
    ]

    operations = [
        migrations.CreateModel(
            name='DemoData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('role', models.CharField(choices=[('owner', 'OWNER'), ('manager', 'MANAGER')], default='owner', max_length=15, verbose_name='role')),
                ('name', models.CharField(max_length=245, verbose_name='name')),
                ('email', models.EmailField(max_length=245, verbose_name='email')),
                ('phone', models.CharField(max_length=20, verbose_name='phone')),
                ('restaurant_name', models.CharField(max_length=245, verbose_name='restaurant name')),
                ('looking_for', models.CharField(choices=[('do', 'DO'), ('atsm', 'ATSM'), ('website', 'WEBSITE')], default='do', max_length=100, verbose_name='service looking for')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
