# Generated by Django 4.1.6 on 2024-09-03 04:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0050_demodata'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(max_length=245, unique=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
