# Generated by Django 4.1.6 on 2024-09-05 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0051_salesmail'),
    ]

    operations = [
        migrations.AddField(
            model_name='bogo',
            name='inflate_percent',
            field=models.IntegerField(default=0),
        ),
    ]
