# Generated by Django 4.1.6 on 2024-09-18 12:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0052_bogo_inflate_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='applied_users',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_one_time_use',
            field=models.BooleanField(default=False),
        ),
    ]
