# Generated by Django 4.1.6 on 2024-10-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0053_voucher_applied_users_voucher_is_one_time_use'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailhistory',
            name='html_content',
            field=models.TextField(blank=True, null=True, verbose_name='html_content'),
        ),
        migrations.AlterField(
            model_name='emailhistory',
            name='message',
            field=models.TextField(blank=True, null=True, verbose_name='message'),
        ),
    ]
