# Generated by Django 4.1.6 on 2024-10-03 11:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0101_restaurant_use_delivery_inflation'),
        ('marketing', '0055_remove_review_menuitem_comment_dislikes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='menuItem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='food.menuitem', verbose_name='menu items'),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True, verbose_name='menu items'),
        ),
    ]
