# Generated by Django 4.1.6 on 2024-10-09 04:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0054_alter_emailhistory_html_content_and_more'),
        ('marketing', '0059_alter_review_review'),
    ]

    operations = [
    ]
