# Generated by Django 4.1.6 on 2024-11-17 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0064_review_created_date_review_modified_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='restaurant_id',
            field=models.IntegerField(default=0),
        ),
    ]
