# Generated by Django 4.1.6 on 2024-12-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0065_review_restaurant_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='available_to',
            field=models.CharField(choices=[('all', 'ALL'), ('members', 'MEMBERS'), ('first_order', 'FIRST_ORDER'), ('second_order', 'SECOND_ORDER'), ('third_order', 'THIRD_ORDER')], default='all', max_length=20, verbose_name='Available To'),
        ),
    ]
