# Generated by Django 4.1.6 on 2025-01-01 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0118_restaurant_is_chatchef_bd'),
        ('marketing', '0066_alter_voucher_available_to'),
    ]

    operations = [
        migrations.CreateModel(
            name='AutoReplyToComments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_reply_to_good_comments', models.BooleanField(default=False, verbose_name='Auto Reply to Good Comments')),
                ('auto_reply_to_bad_comments', models.BooleanField(default=False, verbose_name='Auto Reply to Bad Comments')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.location', verbose_name='Location')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='Restaurant')),
            ],
        ),
    ]
