# Generated by Django 4.1.6 on 2025-01-02 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0067_autoreplytocomments'),
    ]

    operations = [
        migrations.AddField(
            model_name='autoreplytocomments',
            name='voucher_amount',
            field=models.FloatField(default=0, verbose_name='Voucher Amount'),
        ),
    ]
