# Generated by Django 4.1.6 on 2025-01-02 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0068_autoreplytocomments_voucher_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autoreplytocomments',
            name='voucher_amount',
            field=models.IntegerField(default=0, verbose_name='Voucher Amount'),
        ),
    ]
