# Generated by Django 4.1.6 on 2025-01-06 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0069_alter_autoreplytocomments_voucher_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
