# Generated by Django 4.1.6 on 2025-01-21 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0070_review_is_pinned'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='order_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
