# Generated by Django 4.1.6 on 2025-02-05 05:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0121_restaurant_average_rating'),
        ('marketing', '0071_review_order_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='restaurant_id',
        ),
        migrations.AddField(
            model_name='review',
            name='restaurant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='food.restaurant'),
        ),
    ]
