# Generated by Django 4.1.6 on 2025-02-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0072_remove_review_restaurant_id_review_restaurant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voucher',
            name='available_to',
            field=models.CharField(blank=True, choices=[('all', 'ALL'), ('members', 'MEMBERS'), ('first_order', 'FIRST_ORDER'), ('second_order', 'SECOND_ORDER'), ('third_order', 'THIRD_ORDER')], default=None, max_length=20, null=True, verbose_name='Available To'),
        ),
    ]
