# Generated by Django 4.2.19 on 2025-03-18 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0074_bxgy'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxgy',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
