# Generated by Django 4.2.19 on 2025-03-18 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0075_alter_bxgy_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bxgy',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
