# Generated by Django 4.2.19 on 2025-03-18 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0076_alter_bxgy_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bxgy',
            name='id',
        ),
        migrations.AddField(
            model_name='bxgy',
            name='activationcampaign_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='marketing.activationcampaign'),
            preserve_default=False,
        ),
    ]
