# Generated by Django 4.2.19 on 2025-03-18 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0077_remove_bxgy_id_bxgy_activationcampaign_ptr'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BxGy',
        ),
    ]
