# Generated by Django 4.2.19 on 2025-03-18 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0079_bxgy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bxgy',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bxgy',
            name='free_items',
        ),
        migrations.RemoveField(
            model_name='bxgy',
            name='items',
        ),
        migrations.RemoveField(
            model_name='bxgy',
            name='updated_at',
        ),
    ]
