# Generated by Django 4.2.19 on 2025-03-18 16:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0080_remove_bxgy_created_at_remove_bxgy_free_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxgy',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='bxgy',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
    ]
