# Generated by Django 4.2.19 on 2025-03-18 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0128_merge_20250211_0424'),
        ('marketing', '0081_bxgy_created_at_bxgy_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxgy',
            name='free_items',
            field=models.ManyToManyField(blank=True, help_text='Items that can be given for free if different from the bought items.', related_name='bxgy_free_items', to='food.menuitem', verbose_name='Free Items'),
        ),
        migrations.AddField(
            model_name='bxgy',
            name='items',
            field=models.ManyToManyField(blank=True, help_text='Items that customers need to buy to qualify for the offer.', related_name='bxgy_campaigns', to='food.menuitem', verbose_name='Menu Items'),
        ),
    ]
