# Generated by Django 4.2.19 on 2025-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0082_bxgy_free_items_bxgy_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fissionprize',
            name='prize_name',
            field=models.CharField(choices=[('bogo', 'BOGO'), ('bxgy', 'BXGY'), ('percentage', 'PERCENTAGE'), ('fixed', 'FIXED')], default='percentage', max_length=250, verbose_name='prize name'),
        ),
    ]
