# Generated by Django 4.2.19 on 2025-03-21 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0085_bxgy_free_items_bxgy_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bxgy',
            name='free_items',
        ),
        migrations.RemoveField(
            model_name='bxgy',
            name='items',
        ),
    ]
