# Generated by Django 4.2.19 on 2025-03-27 10:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_user_referred_by'),
        ('marketing', '0087_bxgy_free_items_bxgy_items'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcampaign',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.company', verbose_name='Company'),
        ),
    ]
