# Generated by Django 4.2.19 on 2025-04-23 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0088_alter_activationcampaign_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bxgy',
            name='free_items',
        ),
    ]
