# Generated by Django 4.2.19 on 2025-04-23 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0131_restaurant_discount_percentage'),
        ('marketing', '0089_remove_bxgy_free_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxgy',
            name='free_items',
            field=models.ManyToManyField(blank=True, help_text='Items that can be given for free if different from the bought items.', related_name='bxgy_free_items', to='food.menuitem', verbose_name='Free Items'),
        ),
    ]
