# Generated by Django 4.2.19 on 2025-04-23 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0090_bxgy_free_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bxgy',
            name='free_items',
        ),
    ]
