# Generated by Django 4.2.19 on 2025-05-07 17:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('marketing', '0093_remove_bxgy_free_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='ht_voucher_percentage_borne_by_restaurant',
            field=models.FloatField(default=0, help_text='Percentage of the voucher amount that is borne by the restaurant.'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_global',
            field=models.BooleanField(default=False, help_text='If True, this voucher can be used by all users.'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_ht_voucher',
            field=models.BooleanField(default=False, help_text='If True, this voucher is a HT voucher.'),
        ),
        migrations.AlterField(
            model_name='voucher',
            name='applied_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Applied Users'),
        ),
    ]
