# Generated by Django 4.2.19 on 2025-05-07 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0136_merge_20250428_0153'),
        ('marketing', '0094_voucher_ht_voucher_percentage_borne_by_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activationcampaign',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='activationcampaign',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.menu', verbose_name='Menu'),
        ),
        migrations.AlterField(
            model_name='activationcampaign',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant'),
        ),
    ]
