# Generated by Django 4.2.19 on 2025-05-22 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0136_merge_20250428_0153'),
        ('marketing', '0096_voucher_max_uses'),
    ]

    operations = [
        migrations.AddField(
            model_name='bxgy',
            name='free_items',
            field=models.ManyToManyField(blank=True, help_text='Items that can be given for free if different from the bought items.', related_name='bxgy_free_items', to='food.menuitem', verbose_name='Free Items'),
        ),
    ]
