# Generated by Django 4.2.19 on 2025-05-22 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0136_merge_20250428_0153'),
        ('marketing', '0097_bxgy_free_items'),
    ]

    operations = [
        migrations.CreateModel(
            name='BxGyBuyItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.menuitem')),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buy_items', to='marketing.bxgy')),
            ],
        ),
        migrations.CreateModel(
            name='BxGyFreeItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('buy_item_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='free_items', to='marketing.bxgybuyitem')),
                ('free_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.menuitem')),
            ],
        ),
    ]
