# Generated by Django 4.2.19 on 2025-05-22 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0098_bxgybuyitem_bxgyfreeitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bxgy',
            name='free_items',
        ),
    ]
