# Generated by Django 4.2.19 on 2025-05-22 12:04

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0099_remove_bxgy_free_items'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bxgy',
            name='buy',
        ),
        migrations.RemoveField(
            model_name='bxgy',
            name='get',
        ),
        migrations.RemoveField(
            model_name='bxgybuyitem',
            name='buy_item',
        ),
        migrations.RemoveField(
            model_name='bxgyfreeitem',
            name='free_item',
        ),
        migrations.AddField(
            model_name='bxgybuyitem',
            name='buy_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='List of MenuItem IDs to buy', null=True, size=None),
        ),
        migrations.AddField(
            model_name='bxgybuyitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='bxgyfreeitem',
            name='free_items',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.IntegerField(), blank=True, help_text='List of MenuItem IDs free', null=True, size=None),
        ),
        migrations.AddField(
            model_name='bxgyfreeitem',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
