# Generated by Django 4.2.19 on 2025-06-02 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0100_remove_bxgy_buy_remove_bxgy_get_and_more'),
    ]

    operations = [
    ]
