# Generated by Django 4.2.19 on 2025-06-02 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0101_auto_20250601_2319'),
    ]

    operations = [
    ]
