# Generated by Django 4.2.19 on 2025-07-12 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("marketing", "0102_create_bxgybuyitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="voucher",
            name="last_notification_sent_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the last reminder notification was sent",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="voucher",
            name="notification_sent",
            field=models.BooleanField(
                default=False, help_text="Has 48-hour expiry notification been sent?"
            ),
        ),
        migrations.CreateModel(
            name="PlatformCouponExpiryLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("coupon_code", models.CharField(max_length=50)),
                ("coupon_value", models.FloatField()),
                ("expiry_date", models.DateField()),
                ("sent_at", models.DateTimeField()),
                ("status", models.CharField(max_length=20)),
                ("source", models.CharField(default="platform", max_length=50)),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "voucher",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="marketing.voucher",
                    ),
                ),
            ],
        ),
    ]
