# Generated by Django 4.2.19 on 2025-07-12 09:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0103_voucher_last_notification_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="platformcouponexpirylog",
            name="expiry_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
