# Generated by Django 4.2.19 on 2025-07-17 03:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0064_companydiscount_companydiscountuser'),
        ('marketing', '0104_alter_platformcouponexpirylog_expiry_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='company_hungry',
            field=models.ForeignKey(blank=True, help_text='If this is a company voucher, link to the company', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.companydiscount'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_company_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
