# Generated by Django 4.2.19 on 2025-07-17 04:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0106_companydiscount_remove_voucher_company_hungry_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='voucher',
            name='company_hungry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='marketing.companydiscount'),
        ),
        migrations.AddField(
            model_name='voucher',
            name='is_company_voucher',
            field=models.BooleanField(default=False),
        ),
    ]
