# Generated by Django 4.1.6 on 2023-05-17 18:52

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(blank=True, verbose_name='Content')),
                ('message_type', models.CharField(choices=[('user_message', 'USER MESSAGE'), ('system_message', 'SYSTEM MESSAGE')], default='user_message', max_length=15, verbose_name='Message Type')),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2023, 5, 17, 18, 52, 59, 184612, tzinfo=datetime.timezone.utc), verbose_name='Timestamp')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Message',
                'verbose_name_plural': 'Messages',
            },
        ),
    ]
