# Generated by Django 4.1.6 on 2023-12-02 03:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='requested path')),
                ('method', models.CharField(blank=True, max_length=10, null=True, verbose_name='requested method')),
                ('status_code', models.CharField(blank=True, max_length=10, null=True, verbose_name='request status code')),
                ('request_headers', models.TextField(blank=True, null=True, verbose_name='requested header')),
                ('request_body', models.TextField(blank=True, null=True, verbose_name='requested body')),
                ('response_headers', models.TextField(blank=True, null=True, verbose_name='response headers')),
                ('response_body', models.TextField(blank=True, null=True, verbose_name='response body')),
                ('ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='request ip')),
                ('mac', models.CharField(blank=True, max_length=100, null=True, verbose_name='requested mac')),
                ('browser', models.CharField(blank=True, max_length=50, null=True, verbose_name='requested browser')),
                ('os', models.CharField(blank=True, max_length=50, null=True, verbose_name='requested os')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='requested user')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
