# Generated by Django 4.1.6 on 2023-12-02 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requesttracker',
            name='browser',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='requested browser'),
        ),
        migrations.AlterField(
            model_name='requesttracker',
            name='os',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='requested os'),
        ),
    ]
