# Generated by Django 4.1.6 on 2024-07-01 09:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0089_alter_restaurant_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('invite_code', models.CharField(max_length=10, verbose_name='invite code')),
                ('invited_users', models.ManyToManyField(blank=True, related_name='invited_users', to=settings.AUTH_USER_MODEL, verbose_name='invited users')),
                ('joined_users', models.ManyToManyField(blank=True, related_name='joined_user', to=settings.AUTH_USER_MODEL, verbose_name='joined users')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.location', verbose_name='location')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='restaurant')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
