# Generated by Django 4.1.6 on 2024-07-11 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('total', models.PositiveIntegerField(default=0)),
                ('month', models.PositiveIntegerField(default=0)),
                ('today', models.PositiveIntegerField(default=0)),
                ('refer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='referral.referral', verbose_name='refer')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
