# Generated by Django 4.1.6 on 2024-07-30 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referral', '0003_remove_referral_invite_code_invitecodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitecodes',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted')], default='pending', max_length=10),
        ),
    ]
