# Generated by Django 4.1.6 on 2023-06-06 10:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_user_company'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
