# Generated by Django 4.1.6 on 2023-10-26 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='reward_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Reward points'),
        ),
    ]
