# Generated by Django 4.1.6 on 2023-11-13 19:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0054_modifiergroup_otter_id'),
        ('accounts', '0010_user_reward_points'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('last_used_fission', models.DateTimeField(blank=True, null=True, verbose_name='Last Used Fission')),
                ('reward_points', models.PositiveIntegerField(default=0, verbose_name='Reward Points')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Restaurant User',
                'verbose_name_plural': 'Restaurant Users',
            },
        ),
    ]
