# Generated by Django 4.1.6 on 2023-11-20 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_restaurantuser'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='direct_order_only',
            field=models.BooleanField(default=True, verbose_name='Direct order only'),
        ),
    ]
