# Generated by Django 4.1.6 on 2023-11-21 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0014_alter_fissioncampaign_availability'),
        ('accounts', '0012_user_direct_order_only'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='available_lucky_draws',
            field=models.ManyToManyField(blank=True, to='marketing.fissioncampaign', verbose_name='Available Lucky Draws'),
        ),
    ]
