# Generated by Django 4.1.6 on 2024-01-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_useraddress'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='is_default',
            field=models.BooleanField(default=False, verbose_name='Is default'),
        ),
    ]
