# Generated by Django 4.2.10 on 2024-02-29 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_useraddress_is_default'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='next_level',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Next  Level'),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='points_spent',
            field=models.PositiveIntegerField(default=0, verbose_name='Points Spent'),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='remain_point',
            field=models.PositiveIntegerField(blank=True, default=0, null=True, verbose_name='Remain Points'),
        ),
        migrations.AddField(
            model_name='restaurantuser',
            name='rewards_category',
            field=models.CharField(default='Level-1', max_length=15, verbose_name='Level'),
        ),
    ]
