# Generated by Django 4.1.6 on 2024-02-14 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='uid',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='verify id'),
        ),
    ]
