# Generated by Django 4.1.6 on 2024-02-29 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_restaurantuser_next_level_and_more'),
        ('accounts', '0017_user_uid'),
    ]

    operations = [
    ]
