# Generated by Django 5.0.3 on 2024-03-07 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_restaurantuser_next_level_and_more'),
        ('accounts', '0017_user_uid'),
    ]

    operations = [
    ]
