# Generated by Django 5.0.3 on 2024-03-07 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20240307_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurantuser',
            name='rewards_category',
            field=models.CharField(default='Level-0', max_length=15, verbose_name='Level'),
        ),
    ]
