# Generated by Django 4.1.6 on 2024-03-11 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_merge_20240229_1054'),
        ('accounts', '0019_alter_restaurantuser_rewards_category'),
    ]

    operations = [
    ]
