# Generated by Django 4.1.6 on 2024-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0020_merge_20240311_1241'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='reward_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Reward Level'),
        ),
    ]
