# Generated by Django 4.1.6 on 2024-05-28 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='register_code',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Employ Register Code'),
        ),
    ]
