# Generated by Django 4.1.6 on 2024-05-28 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_company_register_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='register_code',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Employ Register Code'),
        ),
    ]
