# Generated by Django 4.1.6 on 2024-07-31 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_user_date_of_birth'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='is_blocked',
            field=models.BooleanField(default=False),
        ),
    ]
