# Generated by Django 4.1.6 on 2024-10-08 01:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_restaurantuser_is_blocked'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_user_contacts_receiver', to='accounts.restaurantuser', verbose_name='receiver')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant_user_contacts_sender', to='accounts.restaurantuser', verbose_name='sender')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
