# Generated by Django 4.1.6 on 2024-11-17 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_alter_user_is_phone_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='agree',
            field=models.BooleanField(default=False, verbose_name='Agree'),
        ),
    ]
