# Generated by Django 4.1.6 on 2024-12-23 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_user_agree'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contact Person'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], default='male', max_length=10, null=True, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Label'),
        ),
    ]
