# Generated by Django 4.1.6 on 2025-02-09 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0032_useraddress_contact_person_useraddress_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraddress',
            name='lat',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Latitude'),
        ),
        migrations.AddField(
            model_name='useraddress',
            name='lng',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, verbose_name='Longitude'),
        ),
    ]
