# Generated by Django 4.1.6 on 2025-02-13 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_useraddress_lat_useraddress_lng'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraddress',
            name='lat',
            field=models.FloatField(blank=True, null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='useraddress',
            name='lng',
            field=models.FloatField(blank=True, null=True, verbose_name='Longitude'),
        ),
    ]
