# Generated by Django 4.1.6 on 2025-02-16 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_alter_useraddress_lat_alter_useraddress_lng'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_sales',
            field=models.BooleanField(default=False, verbose_name='Is_Sales'),
        ),
    ]
