# Generated by Django 4.2.19 on 2025-04-15 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0036_user_referred_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_get_600',
            field=models.BooleanField(default=False, verbose_name='Is get 600'),
        ),
        migrations.AddField(
            model_name='user',
            name='super_power',
            field=models.BooleanField(default=False, verbose_name='Super power'),
        ),
    ]
