# Generated by Django 4.2.19 on 2025-05-06 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_alter_user_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_count_total',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Order Count'),
        ),
    ]
