# Generated by Django 4.2.19 on 2025-05-06 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_user_order_count_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='order_count_total',
            new_name='order_count_total_rk',
        ),
    ]
