# Generated by Django 4.2.19 on 2025-05-06 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0043_remove_user_order_count_total_rk'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='order_count_total_rk',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Order Count'),
        ),
    ]
