# Generated by Django 4.2.19 on 2025-05-14 06:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0044_user_order_count_total_rk"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("employee", "Employee"),
                    ("hotel_owner", "Hotel Owner"),
                    ("n/a", "N/A"),
                ],
                default="n/a",
                max_length=15,
                verbose_name="Role",
            ),
        ),
    ]
