# Generated by Django 4.2.19 on 2025-05-25 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantuser',
            name='auto_accept_orders',
            field=models.BooleanField(default=False, verbose_name='Auto Accept Orders'),
        ),
    ]
