# Generated by Django 4.2.19 on 2025-05-25 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_restaurantuser_auto_accept_orders'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurantuser',
            name='auto_accept_orders',
        ),
    ]
