# Generated by Django 4.2.19 on 2025-06-02 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0047_remove_restaurantuser_auto_accept_orders'),
    ]

    operations = [
        migrations.CreateModel(
            name='QRScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ref', models.CharField(max_length=100)),
                ('ip_address', models.GenericIPAddressField()),
                ('device_id', models.CharField(max_length=255)),
                ('user_agent', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField()),
            ],
            options={
                'unique_together': {('ref', 'device_id')},
            },
        ),
    ]
