# Generated by Django 4.2.19 on 2025-06-02 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0048_qrscan'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='qrscan',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='device_id',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='qrscan',
            name='ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
