# Generated by Django 4.2.19 on 2025-06-01 06:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0048_blockedphonenumber"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="expires_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
