# Generated by Django 4.2.19 on 2025-06-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0049_otp_email_otp_expires_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="otp",
            options={},
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["user", "is_used"], name="accounts_ot_user_id_791635_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["otp", "email"], name="accounts_ot_otp_c5bcd6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["expires_at"], name="accounts_ot_expires_57ad4f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="otp",
            index=models.Index(
                fields=["created_date"], name="accounts_ot_created_3312b4_idx"
            ),
        ),
    ]
