# Generated by Django 4.2.19 on 2025-06-04 04:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_qrscan_unique_together_alter_qrscan_device_id_and_more'),
        ('accounts', '0050_alter_otp_options_otp_accounts_ot_user_id_791635_idx_and_more'),
    ]

    operations = [
    ]
