# Generated by Django 4.2.19 on 2025-06-18 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0049_alter_userevent_user'),
        ('accounts', '0051_merge_20250603_2143'),
    ]

    operations = [
    ]
