# Generated by Django 4.2.19 on 2025-06-22 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0052_merge_20250618_0312"),
        ("accounts", "0052_merge_20250618_1439"),
    ]

    operations = []
