# Generated by Django 4.2.19 on 2025-06-30 06:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_merge_20250623_0215'),
    ]

    operations = [
        migrations.AddField(
            model_name='daurecord',
            name='event_name',
            field=models.CharField(default='app_open', max_length=50),
        ),
        migrations.AddField(
            model_name='userevent',
            name='platform',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='daurecord',
            name='date',
            field=models.DateField(),
        ),
        migrations.AlterUniqueTogether(
            name='daurecord',
            unique_together={('date', 'event_name')},
        ),
        migrations.CreateModel(
            name='UserEngagementSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('segment', models.CharField(choices=[('daily_active', 'Daily Active'), ('weekly_active', 'Weekly Active'), ('monthly_active', 'Monthly Active'), ('lapsed', 'Lapsed')], max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserChurnStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_activity_date', models.DateField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('at_risk', 'At Risk'), ('churned', 'Churned')], max_length=20)),
                ('last_updated', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
