# Generated by Django 4.2.19 on 2025-07-08 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0053_customer_subscription_cancellationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(default=None, max_length=255, unique=True),
        ),
    ]
