# Generated by Django 4.2.19 on 2025-06-30 06:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_daurecord_event_name_userevent_platform_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortRetentionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_label', models.CharField(max_length=20)),
                ('day_offset', models.PositiveIntegerField()),
                ('retained_users', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ConversionFunnelRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opened_app', models.PositiveIntegerField()),
                ('placed_order', models.PositiveIntegerField()),
                ('conversion_rate', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='UserCohort',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cohort_label', models.CharField(max_length=20)),
                ('signup_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
