# Generated by Django 4.2.19 on 2025-07-08 03:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='stripe_subscription_id',
            field=models.CharField(default='temp_sub_id', max_length=255, unique=True),
        ),
    ]
