# Generated by Django 4.2.19 on 2025-07-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0055_cohortretentionrecord_conversionfunnelrecord_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hotel_admin",
            field=models.BooleanField(default=False, verbose_name="Hotel Admin"),
        ),
    ]
