# Generated by Django 4.2.19 on 2025-07-08 03:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_alter_subscription_stripe_subscription_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscription',
            name='stripe_subscription_id',
        ),
    ]
