# Generated by Django 4.2.19 on 2025-07-14 06:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0056_user_hotel_admin"),
        ("accounts", "0060_alter_subscription_current_period_end_and_more"),
    ]

    operations = []
