# Generated by Django 4.2.19 on 2025-07-14 07:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_merge_20250713_2327'),
        ('accounts', '0061_merge_20250714_1218'),
    ]

    operations = [
    ]
