# Generated by Django 4.2.19 on 2025-07-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0106_companydiscount_remove_voucher_company_hungry_and_more'),
        ('accounts', '0064_companydiscount_companydiscountuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='companydiscountuser',
            name='company',
        ),
        migrations.DeleteModel(
            name='CompanyDiscount',
        ),
        migrations.DeleteModel(
            name='CompanyDiscountUser',
        ),
    ]
