# Generated by Django 4.1.6 on 2023-11-10 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0054_modifiergroup_otter_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupInvitationOR',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('platform', models.CharField(max_length=255, verbose_name='platform')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('group_link', models.CharField(max_length=255, unique=True, verbose_name='group link')),
                ('is_active', models.BooleanField(default=False, verbose_name='is active')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
