# Generated by Django 4.1.6 on 2023-11-16 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0054_modifiergroup_otter_id'),
        ('communication', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('contact_no', models.CharField(max_length=15, verbose_name='contact')),
                ('email', models.CharField(max_length=50, verbose_name='mail')),
                ('is_subscribed', models.BooleanField(default=True, verbose_name='is subscribed')),
                ('restaurant', models.ManyToManyField(blank=True, to='food.restaurant', verbose_name='restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
