# Generated by Django 4.1.6 on 2023-11-30 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
        ('communication', '0003_alter_customerinfo_email_alter_customerinfo_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='whatsAppCampaignHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('Audience', models.CharField(max_length=200, verbose_name='audience')),
                ('msg_type', models.CharField(blank=True, max_length=255, verbose_name='msg_type')),
                ('img_link', models.CharField(blank=True, max_length=255, verbose_name='img_link')),
                ('msg_to', models.CharField(blank=True, max_length=255, verbose_name='msg_to')),
                ('body', models.CharField(blank=True, max_length=255, verbose_name='body')),
                ('url', models.CharField(blank=True, max_length=255, verbose_name='url')),
                ('time', models.DateTimeField(verbose_name='time')),
                ('Restaurant', models.ManyToManyField(blank=True, to='food.restaurant', verbose_name='restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
