# Generated by Django 4.1.6 on 2023-12-07 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('communication', '0004_whatsappcampaignhistory'),
    ]

    operations = [
        migrations.RenameField(
            model_name='whatsappcampaignhistory',
            old_name='Restaurant',
            new_name='restaurant',
        ),
        migrations.RemoveField(
            model_name='whatsappcampaignhistory',
            name='Audience',
        ),
        migrations.AddField(
            model_name='whatsappcampaignhistory',
            name='msg_header',
            field=models.CharField(blank=True, max_length=59, verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='img_link',
            field=models.CharField(blank=True, max_length=255, verbose_name='img _link'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='time',
            field=models.DateTimeField(blank=True, verbose_name='time'),
        ),
        migrations.AddField(
            model_name='whatsappcampaignhistory',
            name='audience',
            field=models.CharField(blank=True, max_length=200, verbose_name='audience'),
        ),
    ]
