# Generated by Django 4.1.6 on 2024-04-15 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0071_alter_category_shared_with'),
        ('communication', '0007_emailcampaignhistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailcampaignhistory',
            name='audience',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='audience'),
        ),
        migrations.AlterField(
            model_name='emailcampaignhistory',
            name='from_name',
            field=models.CharField(blank=True, max_length=59, null=True, verbose_name='from_name'),
        ),
        migrations.AlterField(
            model_name='emailcampaignhistory',
            name='htmlPart',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='htmlPart'),
        ),
        migrations.AlterField(
            model_name='emailcampaignhistory',
            name='msg_from',
            field=models.CharField(blank=True, max_length=59, null=True, verbose_name='msg_from'),
        ),
        migrations.AlterField(
            model_name='emailcampaignhistory',
            name='msg_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='msg_to'),
        ),
        migrations.AlterField(
            model_name='emailcampaignhistory',
            name='restaurant',
            field=models.ManyToManyField(to='food.restaurant', verbose_name='restaurant'),
        ),
        migrations.AlterField(
            model_name='emailcampaignhistory',
            name='subject',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='subject'),
        ),
        migrations.AlterField(
            model_name='emailcampaignhistory',
            name='textPart',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='textPart'),
        ),
        migrations.AlterField(
            model_name='emailcampaignhistory',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='emailcampaignhistory',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='url'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='audience',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='audience'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='body',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='body'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='img_link',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='img _link'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='msg_header',
            field=models.CharField(blank=True, max_length=59, null=True, verbose_name='header'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='msg_to',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='msg_to'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='msg_type',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='msg_type'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='restaurant',
            field=models.ManyToManyField(to='food.restaurant', verbose_name='restaurant'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='time'),
        ),
        migrations.AlterField(
            model_name='whatsappcampaignhistory',
            name='url',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='url'),
        ),
    ]
