# Generated by Django 4.1.6 on 2023-10-23 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('food', '0050_alter_restaurant_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='PosDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('pos_type', models.CharField(choices=[('clover', 'clover'), ('toast', 'toast')], max_length=50, verbose_name='pos provide')),
                ('pos_merchant_id', models.CharField(max_length=255, verbose_name='pos merchant or store id')),
                ('employ_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='employ id')),
                ('store_location', models.CharField(blank=True, max_length=255, null=True, verbose_name='store location')),
                ('timezone', models.CharField(blank=True, choices=[('-12:00', '-12:00'), ('-11:00', '-11:00'), ('-10:00', '-10:00'), ('-09:00', '-09:00'), ('-08:00', '-08:00'), ('-07:00', '-07:00'), ('-06:00', '-06:00'), ('-05:00', '-05:00'), ('-04:00', '-04:00'), ('-03:00', '-03:00'), ('-02:00', '-02:00'), ('-01:00', '-01:00'), ('+00:00', '+00:00'), ('+01:00', '+01:00'), ('+02:00', '+02:00'), ('+03:00', '+03:00'), ('+04:00', '+04:00'), ('+05:00', '+05:00'), ('+06:00', '+06:00'), ('+07:00', '+07:00'), ('+08:00', '+08:00'), ('+09:00', '+09:00'), ('+10:00', '+10:00'), ('+11:00', '+11:00'), ('+12:00', '+12:00')], max_length=10, null=True, verbose_name='store timezone')),
                ('authenticated_code', models.CharField(blank=True, max_length=255, null=True, verbose_name='authenticated code')),
                ('app_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='app id')),
                ('app_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='app secret')),
                ('partner_key', models.CharField(blank=True, max_length=255, null=True, verbose_name='partner key secret')),
                ('access_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='access token')),
                ('refresh_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='refresh token')),
                ('event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='event id')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='restaurant id')),
            ],
            options={
                'verbose_name': 'Restaurant Pos Details',
                'verbose_name_plural': 'Restaurants Pos Details',
                'ordering': ['-id'],
            },
        ),
    ]
