# Generated by Django 4.1.6 on 2023-10-26 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS_logs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('logs', models.TextField(blank=True, null=True, verbose_name='logs')),
            ],
            options={
                'verbose_name': 'Pos Log',
                'verbose_name_plural': 'Pos Logs',
                'ordering': ['-id'],
            },
        ),
    ]
