# Generated by Django 4.2.19 on 2025-05-15 05:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0003_hotel_owner"),
    ]

    operations = [
        migrations.AddField(
            model_name="hotelreview",
            name="booking",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hotel.booking",
            ),
        ),
    ]
