# Generated by Django 4.2.19 on 2025-05-17 10:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotel", "0005_coupon_hoteltag_searchsuggestion_hotel_is_promoted_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HotelSearchHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(blank=True, max_length=100, null=True)),
                ("city", models.CharField(max_length=100)),
                ("checkin", models.DateField()),
                ("checkout", models.DateField()),
                ("adults", models.PositiveSmallIntegerField(default=1)),
                ("children", models.PositiveSmallIntegerField(default=0)),
                ("rooms", models.PositiveSmallIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterUniqueTogether(
            name="hotelviewhistory",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="hotelviewhistory",
            constraint=models.UniqueConstraint(
                fields=("user", "hotel", "session_id"), name="unique_view_per_session"
            ),
        ),
        migrations.AddField(
            model_name="hotelsearchhistory",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
