# Generated by Django 4.2.19 on 2025-05-17 14:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0006_hotelsearchhistory_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nearbyplace",
            name="icon",
        ),
        migrations.AddField(
            model_name="nearbyplace",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name="nearbyplace",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="nearbyplace",
            name="distance_m",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="nearbyplace",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddIndex(
            model_name="nearbyplace",
            index=models.Index(
                fields=["hotel", "distance_m"], name="hotel_nearb_hotel_i_d04f51_idx"
            ),
        ),
    ]
