# Generated by Django 4.2.19 on 2025-05-17 16:35

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0007_remove_nearbyplace_icon_nearbyplace_latitude_and_more"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="nearbyplace",
            name="hotel_nearb_hotel_i_d04f51_idx",
        ),
        migrations.RemoveField(
            model_name="nearbyplace",
            name="distance_m",
        ),
        migrations.AddIndex(
            model_name="nearbyplace",
            index=models.Index(fields=["hotel"], name="hotel_nearb_hotel_i_d3040a_idx"),
        ),
    ]
