# Generated by Django 4.2.19 on 2025-05-18 03:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0008_remove_nearbyplace_hotel_nearb_hotel_i_d04f51_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="guest",
            name="user_type",
            field=models.CharField(
                choices=[("individual", "Individual"), ("corporate", "Corporate")],
                default="individual",
                max_length=20,
            ),
        ),
    ]
