# Generated by Django 4.2.19 on 2025-05-18 03:54

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0009_guest_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bookingpayment",
            name="payment_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
