# Generated by Django 4.2.19 on 2025-05-18 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0010_alter_bookingpayment_payment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="early_checkin_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="extra_bed_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="late_checkout_fee",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="refundable_until_days",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
