# Generated by Django 4.2.19 on 2025-05-18 16:26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0011_roomtype_early_checkin_fee_roomtype_extra_bed_fee_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="number_of_adults",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="booking",
            name="number_of_children",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
