# Generated by Django 4.2.19 on 2025-05-19 09:29

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotel", "0012_booking_number_of_adults_booking_number_of_children"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="hotel",
            options={},
        ),
        migrations.RemoveIndex(
            model_name="hotel",
            name="hotel_hotel_city_3da5ba_idx",
        ),
        migrations.RemoveIndex(
            model_name="hotel",
            name="hotel_hotel_review__190b52_idx",
        ),
        migrations.RemoveIndex(
            model_name="hotel",
            name="hotel_hotel_base_pr_ec71d2_idx",
        ),
        migrations.RemoveIndex(
            model_name="hotel",
            name="hotel_hotel_latitud_8b16ef_idx",
        ),
        migrations.RemoveIndex(
            model_name="hotel",
            name="hotel_hotel_name_7bbf9d_idx",
        ),
        migrations.RemoveIndex(
            model_name="hotel",
            name="hotel_hotel_is_acti_940282_idx",
        ),
        migrations.RemoveIndex(
            model_name="hotel",
            name="hotel_hotel_star_ra_f62a6a_idx",
        ),
        migrations.AlterUniqueTogether(
            name="hotel",
            unique_together={("owner", "name", "address")},
        ),
        migrations.AlterUniqueTogether(
            name="roomtype",
            unique_together={("hotel", "name")},
        ),
    ]
