# Generated by Django 4.2.19 on 2025-05-20 17:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0014_alter_hotelsearchhistory_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="roomtype",
            name="max_adults",
            field=models.PositiveSmallIntegerField(default=2),
        ),
        migrations.AddField(
            model_name="roomtype",
            name="max_children",
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
