# Generated by Django 4.2.19 on 2025-05-26 04:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0016_roomtype_hourly_price_roomtype_is_hourly"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="booking_type",
            field=models.CharField(
                choices=[("daily", "Daily"), ("hourly", "Hourly")],
                default="daily",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="hours",
            field=models.PositiveIntegerField(
                blank=True, help_text="Only applicable for hourly bookings", null=True
            ),
        ),
    ]
