# Generated by Django 4.2.19 on 2025-05-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0017_booking_booking_type_booking_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="check_in_time",
            field=models.TimeField(
                blank=True, help_text="Only for hourly bookings", null=True
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="check_out_time",
            field=models.TimeField(
                blank=True, help_text="Only for hourly bookings", null=True
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_in_time"], name="hotel_booki_check_i_1e063b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["check_out_time"], name="hotel_booki_check_o_28ad28_idx"
            ),
        ),
    ]
