# Generated by Django 4.2.19 on 2025-05-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0018_booking_check_in_time_booking_check_out_time_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="extra_bed_count_per_room",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of extra beds per room"
            ),
        ),
        migrations.AddField(
            model_name="booking",
            name="extra_bed_rooms_count",
            field=models.PositiveIntegerField(
                default=0, help_text="Number of rooms with extra beds"
            ),
        ),
    ]
