# Generated by Django 4.2.19 on 2025-05-30 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0019_booking_extra_bed_count_per_room_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="booking_source",
            field=models.CharField(
                choices=[
                    ("walk_in", "Walk-In by Staff"),
                    ("guest_self_qr", "Guest Self Check-In"),
                    ("online", "Online/Website"),
                    ("phone", "Phone Booking"),
                    ("third_party", "Third Party"),
                ],
                default="walk_in",
                max_length=50,
            ),
        ),
        migrations.CreateModel(
            name="RoomHourlyAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("available_rooms", models.PositiveSmallIntegerField(default=0)),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hourly_availability",
                        to="hotel.roomtype",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["date", "start_time", "end_time"],
                        name="hotel_roomh_date_001261_idx",
                    ),
                    models.Index(
                        fields=["room_type", "date"],
                        name="hotel_roomh_room_ty_73fa1d_idx",
                    ),
                ],
                "unique_together": {("room_type", "date", "start_time", "end_time")},
            },
        ),
    ]
