# Generated by Django 4.2.19 on 2025-05-31 07:38

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0020_alter_booking_booking_source_roomhourlyavailability"),
    ]

    operations = [
        migrations.CreateModel(
            name="BookingRoomItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number_of_rooms", models.PositiveIntegerField(default=1)),
                ("extra_bed_rooms_count", models.PositiveIntegerField(default=0)),
                ("extra_bed_count_per_room", models.PositiveIntegerField(default=0)),
                (
                    "base_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "total_price",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "extra_bed_fee_total",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=10
                    ),
                ),
                (
                    "booking",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="room_items",
                        to="hotel.booking",
                    ),
                ),
                (
                    "room_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="hotel.roomtype"
                    ),
                ),
            ],
        ),
    ]
