# Generated by Django 4.2.19 on 2025-05-31 10:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0021_bookingroomitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="bookings",
                to="hotel.roomtype",
            ),
        ),
    ]
