# Generated by Django 4.2.19 on 2025-05-31 13:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0022_alter_booking_room_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(
                fields=["hotel", "check_in_date", "check_out_date"],
                name="idx_hotel_checkin_checkout",
            ),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["guest", "status"], name="idx_guest_status"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["booking_type"], name="idx_booking_type"),
        ),
        migrations.AddIndex(
            model_name="booking",
            index=models.Index(fields=["payment_status"], name="idx_payment_status"),
        ),
        migrations.AddIndex(
            model_name="bookingcoupon",
            index=models.Index(
                fields=["coupon"], name="hotel_booki_coupon__e93393_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingcoupon",
            index=models.Index(
                fields=["booking"], name="hotel_booki_booking_cb0cc4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingcoupon",
            index=models.Index(
                fields=["coupon", "booking"], name="hotel_booki_coupon__cc1b53_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingroomitem",
            index=models.Index(
                fields=["booking"], name="hotel_booki_booking_a66826_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bookingroomitem",
            index=models.Index(
                fields=["room_type"], name="hotel_booki_room_ty_369ec1_idx"
            ),
        ),
    ]
