# Generated by Django 4.2.19 on 2025-07-08 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("hotel", "0024_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="guest",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="hotel.guest",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="hotel",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="bookings",
                to="hotel.hotel",
            ),
        ),
    ]
