# Generated by Django 4.1.6 on 2023-12-14 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
        ('reward', '0002_alter_reward_options_reward_amount_reward_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcondition',
            name='items',
            field=models.ManyToManyField(blank=True, to='food.menuitem', verbose_name='Items'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='categories',
            field=models.ManyToManyField(blank=True, to='food.category', verbose_name='Categories'),
        ),
        migrations.AlterField(
            model_name='reward',
            name='items',
            field=models.ManyToManyField(blank=True, to='food.menuitem', verbose_name='Menu items'),
        ),
    ]
