# Generated by Django 4.1.6 on 2023-12-16 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_restaurantuser_available_lucky_draws'),
        ('reward', '0003_alter_additionalcondition_items_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardgroup',
            name='company',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Company'),
        ),
    ]
