# Generated by Django 4.1.6 on 2023-12-17 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0005_userreward'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='is_claimed',
            field=models.BooleanField(default=False, verbose_name='Is claimed'),
        ),
    ]
