# Generated by Django 4.1.6 on 2023-12-17 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0006_userreward_is_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='bogo_type',
            field=models.CharField(choices=[('any_dish', 'ANY_DISH'), ('selected_category', 'SELECTED_CATEGORY'), ('selected_dishes', 'SELECTED_DISHES')], default='selected_dishes', max_length=20, verbose_name='Bogo Type'),
        ),
    ]
