# Generated by Django 4.1.6 on 2023-12-26 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0008_alter_userreward_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalcondition',
            name='reward_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reward.rewardgroup', verbose_name='Reward Group'),
        ),
    ]
