# Generated by Django 4.1.6 on 2024-01-05 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0010_alter_userreward_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='additionalcondition',
            options={'ordering': ['-id'], 'verbose_name': 'Additional Condition', 'verbose_name_plural': 'Additional Conditions'},
        ),
        migrations.AlterModelOptions(
            name='reward',
            options={'ordering': ['-id'], 'verbose_name': 'Reward', 'verbose_name_plural': 'Rewards'},
        ),
        migrations.AlterModelOptions(
            name='rewardgroup',
            options={'ordering': ['-id'], 'verbose_name': 'Reward Group', 'verbose_name_plural': 'Reward Groups'},
        ),
        migrations.AlterModelOptions(
            name='userreward',
            options={'ordering': ['-id'], 'verbose_name': 'User Reward', 'verbose_name_plural': 'User Rewards'},
        ),
    ]
