# Generated by Django 4.1.6 on 2024-01-22 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0011_alter_additionalcondition_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='delivery_discount',
            field=models.FloatField(default=0, verbose_name='Delivery discount'),
        ),
    ]
