# Generated by Django 4.2.10 on 2024-02-23 02:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0061_alter_menu_options_menu_showing'),
        ('reward', '0012_reward_delivery_discount'),
    ]

    operations = [
        migrations.CreateModel(
            name='RewardManage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('total_reward_point', models.PositiveIntegerField(default=0, verbose_name='Total points')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='Restaurant')),
                ('reward_group', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reward.rewardgroup', verbose_name='Reward Group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'RewardManage',
                'verbose_name_plural': 'RewardManaes',
                'ordering': ['-id'],
            },
        ),
    ]
