# Generated by Django 4.2.10 on 2024-02-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0013_rewardmanage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardmanage',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='rewardmanage',
            name='modified_date',
        ),
        migrations.AlterField(
            model_name='rewardmanage',
            name='total_reward_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Total Reward points'),
        ),
    ]
