# Generated by Django 4.2.10 on 2024-02-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0014_remove_rewardmanage_created_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardmanage',
            options={'ordering': ['-id'], 'verbose_name': 'RewardManage', 'verbose_name_plural': 'RewardManages'},
        ),
        migrations.RenameField(
            model_name='rewardmanage',
            old_name='reward_group',
            new_name='reward_grp',
        ),
        migrations.AddField(
            model_name='rewardmanage',
            name='min_reward_point',
            field=models.PositiveIntegerField(default=0, verbose_name='Minimum Reward points'),
        ),
    ]
