# Generated by Django 4.1.6 on 2024-03-20 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0015_alter_rewardmanage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reward',
            name='reward_points_worth',
            field=models.PositiveIntegerField(default=0, verbose_name='Reward points worth of'),
        ),
    ]
