# Generated by Django 4.1.6 on 2024-03-26 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0016_reward_reward_points_worth'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='expiry_date',
            field=models.DateField(blank=True, null=True, verbose_name='Expiry date'),
        ),
    ]
