# Generated by Django 4.1.6 on 2024-03-27 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0018_remove_rewardmanage_min_reward_point_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rewardmanage',
            old_name='reward_grp',
            new_name='reward_group',
        ),
    ]
