# Generated by Django 4.1.6 on 2024-04-09 19:02

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0071_alter_category_shared_with'),
        ('accounts', '0020_merge_20240311_1241'),
        ('reward', '0019_rename_reward_grp_rewardmanage_reward_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardmanage',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rewardmanage',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.CreateModel(
            name='RewardLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('min_points', models.PositiveIntegerField(default=0, verbose_name='Min points')),
                ('max_points', models.PositiveIntegerField(default=0, verbose_name='Max points')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Logo Image')),
                ('background_image', models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Background Image')),
                ('company', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Company')),
                ('restaurant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant')),
            ],
            options={
                'verbose_name': 'Reward level',
                'verbose_name_plural': 'Reward levels',
            },
        ),
        migrations.AddField(
            model_name='rewardmanage',
            name='reward_level',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reward_manages', to='reward.rewardlevel', verbose_name='Reward Level'),
        ),
    ]
