# Generated by Django 4.1.6 on 2024-04-09 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0020_rewardmanage_created_date_rewardmanage_modified_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardmanage',
            name='company',
        ),
    ]
