# Generated by Django 4.1.6 on 2024-04-09 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0021_remove_rewardmanage_company'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardlevel',
            options={'ordering': ['-id'], 'verbose_name': 'Reward level', 'verbose_name_plural': 'Reward levels'},
        ),
    ]
