# Generated by Django 4.1.6 on 2024-04-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0022_alter_rewardlevel_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='rewardlevel',
            options={'ordering': ['-min_points'], 'verbose_name': 'Reward level', 'verbose_name_plural': 'Reward levels'},
        ),
        migrations.AddField(
            model_name='rewardlevel',
            name='reward_level',
            field=models.PositiveIntegerField(default=0, verbose_name='Reward Level'),
        ),
    ]
