# Generated by Django 4.1.6 on 2024-06-28 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0023_alter_rewardlevel_options_rewardlevel_reward_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('single_dish', 'SINGLE_DISH'), ('multiple_dish', 'MULTIPLE_DISH'), ('bogo', 'BOGO'), ('coupon', 'COUPON'), ('reward_point', 'REWARD_POINT')], default='single_dish', max_length=25, verbose_name='Reward Type'),
        ),
    ]
