# Generated by Django 4.1.6 on 2024-09-06 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0025_alter_userreward_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardgroup',
            name='deleted',
            field=models.BooleanField(default=False),
        ),
    ]
