# Generated by Django 4.1.6 on 2024-09-17 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0026_rewardgroup_deleted'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='given_for_not_order_last_x_days',
            field=models.BooleanField(default=False),
        ),
    ]
