# Generated by Django 4.1.6 on 2024-10-29 04:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0103_restaurant_accept_scheduled_order'),
        ('reward', '0027_userreward_given_for_not_order_last_x_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardgroup',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location'),
        ),
    ]
