# Generated by Django 4.1.6 on 2025-01-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0028_rewardgroup_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userreward',
            name='audience',
            field=models.CharField(choices=[('first_order', 'First Order'), ('second_order', 'Second Order'), ('third_order', 'Third Order')], default='first_order', max_length=50, verbose_name='Audience'),
        ),
    ]
