# Generated by Django 4.1.6 on 2025-02-24 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0029_userreward_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreward',
            name='audience',
            field=models.CharField(choices=[('none', 'None'), ('first_order', 'First Order'), ('second_order', 'Second Order'), ('third_order', 'Third Order')], default='first_order', max_length=50, verbose_name='Audience'),
        ),
    ]
