# Generated by Django 4.1.6 on 2025-02-24 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0031_alter_userreward_audience'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardgroup',
            name='platform',
            field=models.CharField(choices=[('all', 'ALL'), ('chatchef', 'CHATCHEF'), ('remotekitchen', 'REMOTEKITCHEN')], default='all', max_length=20, verbose_name='Platform'),
        ),
    ]
