# Generated by Django 4.1.6 on 2025-02-24 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0032_rewardgroup_platform'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rewardgroup',
            name='platform',
        ),
        migrations.AddField(
            model_name='userreward',
            name='platform',
            field=models.CharField(choices=[('all', 'ALL'), ('chatchef', 'CHATCHEF'), ('remotekitchen', 'REMOTEKITCHEN')], default='all', max_length=20, verbose_name='Platform'),
        ),
    ]
