# Generated by Django 4.2.19 on 2025-03-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0033_remove_rewardgroup_platform_userreward_platform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='reward_type',
            field=models.CharField(choices=[('single_dish', 'SINGLE_DISH'), ('multiple_dish', 'MULTIPLE_DISH'), ('bogo', 'BOGO'), ('bxgy', 'BXGY'), ('coupon', 'COUPON'), ('reward_point', 'REWARD_POINT')], default='single_dish', max_length=25, verbose_name='Reward Type'),
        ),
    ]
