# Generated by Django 4.2.19 on 2025-03-27 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0034_alter_reward_reward_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userreward',
            name='audience',
            field=models.CharField(blank=True, choices=[('none', 'None'), ('all', 'All'), ('first_order', 'First Order'), ('second_order', 'Second Order'), ('third_order', 'Third Order')], default='none', max_length=50, null=True, verbose_name='Audience'),
        ),
    ]
