# Generated by Django 4.2.19 on 2025-05-01 15:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0136_merge_20250428_0153'),
        ('reward', '0036_alter_userreward_location_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocalDeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('deal_price', models.DecimalField(decimal_places=2, help_text='Final price user pays', max_digits=10)),
                ('percentage_off', models.PositiveIntegerField(default=0)),
                ('offer_type', models.CharField(choices=[('percentage', 'Percentage'), ('flat', 'Flat'), ('bogo', 'BOGO')], default='percentage', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='For % or $ off or BOGO trigger count', max_digits=6)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('purchase_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('times_purchased', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location')),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.menuitem')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
