# Generated by Django 4.2.19 on 2025-05-04 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0037_localdeal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='localdeal',
            name='amount',
        ),
        migrations.RemoveField(
            model_name='localdeal',
            name='deal_price',
        ),
        migrations.RemoveField(
            model_name='localdeal',
            name='percentage_off',
        ),
        migrations.AddField(
            model_name='localdeal',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Total discount amount applied to the item', max_digits=6),
        ),
    ]
