# Generated by Django 4.2.19 on 2025-05-04 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0038_remove_localdeal_amount_remove_localdeal_deal_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='localdeal',
            name='deal_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Final price user pays', max_digits=10),
        ),
    ]
