# Generated by Django 4.2.19 on 2025-05-07 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0040_localdeal_main_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='localdeal',
            name='deal_type',
            field=models.CharField(choices=[('special_discount', 'Special Discount'), ('normal_discount', 'Normal Discount')], default='normal_discount', help_text='Type of the deal || special discount must be special then normal discount', max_length=20),
        ),
    ]
