# Generated by Django 4.2.19 on 2025-05-07 17:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0044_user_order_count_total_rk'),
        ('food', '0136_merge_20250428_0153'),
        ('reward', '0041_localdeal_deal_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reward',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant'),
        ),
        migrations.AlterField(
            model_name='rewardgroup',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.company', verbose_name='Company'),
        ),
        migrations.AlterField(
            model_name='rewardgroup',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='rewardgroup',
            name='restaurant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.restaurant', verbose_name='Restaurant'),
        ),
    ]
