# Generated by Django 4.2.19 on 2025-06-15 03:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("reward", "0042_alter_reward_restaurant_alter_rewardgroup_company_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="RetentionConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reward_group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="reward.rewardgroup",
                    ),
                ),
            ],
            options={
                "verbose_name": "Retention Config",
                "verbose_name_plural": "Retention Configs",
                "ordering": ["-created_at"],
            },
        ),
    ]
