# Generated by Django 4.2.19 on 2025-06-28 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("reward", "0043_retentionconfig"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="rewardgroup",
            index=models.Index(
                fields=["validity_type"], name="reward_rewa_validit_9fd77a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rewardgroup",
            index=models.Index(
                fields=["validity_date"], name="reward_rewa_validit_44f174_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="rewardgroup",
            index=models.Index(
                fields=["deleted"], name="reward_rewa_deleted_d93872_idx"
            ),
        ),
    ]
