# Generated by Django 4.1.6 on 2023-05-16 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('food', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='category',
            field=models.ManyToManyField(blank=True, to='food.category', verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='images',
            field=models.ManyToManyField(blank=True, to='food.image', verbose_name='Images'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Owner'),
        ),
    ]
