# Generated by Django 4.1.6 on 2023-05-16 09:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_alter_menuitem_category_alter_menuitem_images_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='receive_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 5, 16, 9, 56, 36, 712765, tzinfo=datetime.timezone.utc), verbose_name='Receive Date'),
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
