# Generated by Django 4.1.6 on 2023-05-16 10:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_order_receive_date_alter_category_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='receive_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Receive Date'),
        ),
    ]
