# Generated by Django 4.1.6 on 2023-05-26 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0007_location'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['-id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='cuisinetype',
            options={'ordering': ['-id'], 'verbose_name': 'Cuisine Type', 'verbose_name_plural': 'Cuisine Types'},
        ),
        migrations.AlterModelOptions(
            name='image',
            options={'ordering': ['-id'], 'verbose_name': 'Image', 'verbose_name_plural': 'Images'},
        ),
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['-id'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['-id'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['-id'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-id'], 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['-id'], 'verbose_name': 'Order Item', 'verbose_name_plural': 'Order Items'},
        ),
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ['-id'], 'verbose_name': 'Restaurant', 'verbose_name_plural': 'Restaurants'},
        ),
    ]
