# Generated by Django 4.1.6 on 2023-05-26 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0008_alter_category_options_alter_cuisinetype_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours',
            field=models.JSONField(default=list, verbose_name='Opening Hours'),
        ),
    ]
