# Generated by Django 4.1.6 on 2023-05-26 18:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0009_alter_restaurant_opening_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='hours',
            field=models.JSONField(blank=True, default=list, verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours',
            field=models.JSONField(blank=True, default=list, verbose_name='Opening Hours'),
        ),
        migrations.CreateModel(
            name='ModifierGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('requirement_status', models.CharField(blank=True, default='optional', max_length=15, verbose_name='Requirement status')),
                ('modifier_limit', models.IntegerField(blank=True, default=-1, verbose_name='Modifier limit')),
                ('item_limit', models.IntegerField(blank=True, default=-1, verbose_name='Item limit')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.menu', verbose_name='Menu')),
                ('modifier_items', models.ManyToManyField(related_name='modifier_items_related', to='food.menuitem', verbose_name='Modifier items')),
                ('used_by', models.ManyToManyField(related_name='modifiers', to='food.menuitem', verbose_name='Used by')),
            ],
            options={
                'verbose_name': 'Modifier Group',
                'verbose_name_plural': 'Modifier Groups',
                'ordering': ['-id'],
            },
        ),
    ]
