# Generated by Django 4.1.6 on 2023-05-31 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0012_alter_category_restaurant_alter_menuitem_restaurant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='locations',
            field=models.ManyToManyField(to='food.location', verbose_name='Location'),
        ),
    ]
