# Generated by Django 4.1.6 on 2023-05-31 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0013_menu_locations'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpeningHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('day_index', models.CharField(max_length=10, verbose_name='Day Index')),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
            ],
            options={
                'verbose_name': 'Opening Hour',
                'verbose_name_plural': 'Opening Hours',
            },
        ),
        migrations.RemoveField(
            model_name='location',
            name='hours',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='opening_hours',
        ),
        migrations.AddField(
            model_name='location',
            name='opening_hours',
            field=models.ManyToManyField(to='food.openinghour', verbose_name='Hours'),
        ),
        migrations.AddField(
            model_name='menu',
            name='opening_hours',
            field=models.ManyToManyField(to='food.openinghour', verbose_name='Opening Hours'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='opening_hours',
            field=models.ManyToManyField(to='food.openinghour', verbose_name='Opening Hours'),
        ),
    ]
