# Generated by Django 4.1.6 on 2023-05-31 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0014_openinghour_remove_location_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='locations',
            field=models.ManyToManyField(blank=True, to='food.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='locations',
            field=models.ManyToManyField(blank=True, to='food.location', verbose_name='Location'),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='locations',
            field=models.ManyToManyField(blank=True, to='food.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='opening_hours',
            field=models.ManyToManyField(blank=True, to='food.openinghour', verbose_name='Hours'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='cuisine_types',
            field=models.ManyToManyField(blank=True, to='food.cuisinetype', verbose_name='Cuisine Types'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='locations',
            field=models.ManyToManyField(blank=True, to='food.location', verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='opening_hours',
            field=models.ManyToManyField(blank=True, to='food.openinghour', verbose_name='Opening Hours'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='opening_hours',
            field=models.ManyToManyField(blank=True, to='food.openinghour', verbose_name='Opening Hours'),
        ),
    ]
