# Generated by Django 4.1.6 on 2023-06-03 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0015_category_locations_menuitem_locations_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='menu',
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ManyToManyField(blank=True, to='food.menu', verbose_name='Menu'),
        ),
    ]
