# Generated by Django 4.1.6 on 2023-06-08 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_extradata'),
        ('food', '0016_remove_category_menu_category_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='extra_descriptions',
            field=models.ManyToManyField(blank=True, related_name='description_of_menu', to='core.extradata', verbose_name='Extra descriptions'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='extra_names',
            field=models.ManyToManyField(blank=True, related_name='name_of_menu', to='core.extradata', verbose_name='Extra names'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='virtual_price',
            field=models.FloatField(blank=True, default=0, verbose_name='Virtual price'),
        ),
    ]
