# Generated by Django 4.1.6 on 2023-06-09 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0017_menuitem_extra_descriptions_menuitem_extra_names_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='menu',
        ),
        migrations.AddField(
            model_name='category',
            name='menu',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='food.menu', verbose_name='Menu'),
        ),
    ]
