# Generated by Django 4.1.6 on 2023-06-10 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0018_remove_category_menu_category_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
