# Generated by Django 4.1.6 on 2023-06-20 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0019_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='original_image',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_image_of', to='food.image', verbose_name='Original image'),
        ),
    ]
