# Generated by Django 4.1.6 on 2023-06-21 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0020_menuitem_original_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='local_url',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/', verbose_name='Local URL'),
        ),
    ]
