# Generated by Django 4.1.6 on 2023-06-26 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0021_alter_image_local_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='avatar_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='avatar_of_restaurant', to='food.image', verbose_name='Avatar'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='banner_image',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banner_of_restaurant', to='food.image', verbose_name='Banner'),
        ),
    ]
