# Generated by Django 4.1.6 on 2023-06-27 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0022_restaurant_avatar_image_restaurant_banner_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuitem',
            name='original_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='original_image_of', to='food.image', verbose_name='Original image'),
        ),
    ]
