# Generated by Django 4.1.6 on 2023-06-28 10:32
import uuid

from django.db import migrations


def gen_uuid(apps, schema_editor):
    model_names = ['Category', 'Location', 'Menu', 'MenuItem', 'ModifierGroup', 'Restaurant']
    # MyModel = apps.get_model('myapp', 'MyModel')
    models = [apps.get_model('food', name) for name in model_names]
    for model in models:
        for row in model.objects.all():
            row.uid = uuid.uuid4()
            row.save()


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0024_category_slug_category_uid_location_direct_order_and_more'),
    ]

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
