# Generated by Django 4.1.6 on 2023-06-28 10:33
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('food', '0025_auto_20230628_1032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='category',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Uid'),
        ),
        migrations.AlterField(
            model_name='location',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='location',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Uid'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Uid'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Uid'),
        ),
        migrations.AlterField(
            model_name='modifiergroup',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='modifiergroup',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Uid'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='slug',
            field=models.SlugField(blank=True, max_length=250, unique=True, verbose_name='Slug'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='uid',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False, unique=True, verbose_name='Uid'),
        ),
    ]
