# Generated by Django 4.1.6 on 2023-06-28 21:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0027_order_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='menu_item',
        ),
        migrations.RemoveField(
            model_name='orderitem',
            name='order',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
