# Generated by Django 4.1.6 on 2023-07-31 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0028_remove_orderitem_menu_item_remove_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='currency',
            field=models.CharField(default='USD', max_length=200, verbose_name='Currency'),
        ),
    ]
