# Generated by Django 4.1.6 on 2023-08-17 19:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0030_restaurant_payment_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghour',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='openinghour',
            name='start_time',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is Available'),
        ),
        migrations.AlterField(
            model_name='openinghour',
            name='day_index',
            field=models.CharField(choices=[('mon', 'MON'), ('tue', 'TUE'), ('wed', 'WED'), ('thu', 'THU'), ('fri', 'FRI'), ('sat', 'SAT'), ('sun', 'SUN'), ('all', 'ALL')], max_length=10, verbose_name='Day Index'),
        ),
        migrations.CreateModel(
            name='TimeTable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(verbose_name='Start time')),
                ('end_time', models.TimeField(verbose_name='End time')),
                ('opening_hour', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.openinghour', verbose_name='Opening_hour')),
            ],
            options={
                'verbose_name': 'TimeTable',
                'verbose_name_plural': 'TimeTables',
            },
        ),
    ]
