# Generated by Django 4.1.6 on 2023-08-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0031_remove_openinghour_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='have_nuts',
            field=models.BooleanField(default=False, verbose_name='Have Nuts'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_glutenfree',
            field=models.BooleanField(default=False, verbose_name='Is Glutenfree'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegan',
            field=models.BooleanField(default=False, verbose_name='Is Vegan'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='is_vegetarian',
            field=models.BooleanField(default=False, verbose_name='Is Vegetarian'),
        ),
    ]
