# Generated by Django 4.1.6 on 2023-09-14 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0032_menuitem_have_nuts_menuitem_is_glutenfree_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='is_close',
            field=models.BooleanField(default=False, verbose_name='Opening Status'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number'),
        ),
    ]
