# Generated by Django 4.1.6 on 2023-09-18 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0033_openinghour_is_close_restaurant_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openinghour',
            name='is_close',
        ),
    ]
