# Generated by Django 4.1.6 on 2023-09-22 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0034_remove_openinghour_is_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='otter_auth_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='otter store id'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='otter_client_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='otter client id'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='otter_client_secret',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='otter client secret'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='otter_x_store_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='otter store id'),
        ),
    ]
