# Generated by Django 4.1.6 on 2023-09-26 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0034_remove_openinghour_is_close'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='doordash_external_store_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Doordash external store ID'),
        ),
    ]
