# Generated by Django 4.1.6 on 2023-09-26 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0035_restaurant_doordash_external_store_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='doordash_external_store_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='Doordash external store ID'),
        ),
        migrations.AddField(
            model_name='location',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='location',
            name='phone',
            field=models.CharField(blank=True, max_length=20, verbose_name='Phone number'),
        ),
    ]
