# Generated by Django 4.1.6 on 2023-09-22 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0035_restaurant_otter_auth_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='otter_x_event_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='otter event id'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='otter_auth_token',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='otter auth token'),
        ),
    ]
