# Generated by Django 4.1.6 on 2023-09-23 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0036_restaurant_otter_x_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='otter_category_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='otter category id'),
        ),
    ]
