# Generated by Django 4.1.6 on 2023-09-25 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0037_category_otter_category_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='otter_menu_id',
            field=models.CharField(blank=True, max_length=100, verbose_name='otter menu id'),
        ),
    ]
