# Generated by Django 4.1.6 on 2023-09-25 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0038_menu_otter_menu_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='otter_item_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='otter item id'),
        ),
    ]
