# Generated by Django 4.1.6 on 2023-09-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0041_alter_menuitem_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='otter_image_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='otter image id'),
        ),
    ]
