# Generated by Django 4.1.6 on 2023-09-28 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0036_location_doordash_external_store_id_location_email_and_more'),
        ('food', '0042_image_otter_image_id'),
    ]

    operations = [
    ]
