# Generated by Django 4.1.6 on 2023-09-30 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0043_merge_20230930_0349'),
    ]

    operations = [
        migrations.AddField(
            model_name='openinghour',
            name='is_close',
            field=models.BooleanField(default=False, verbose_name='Opening Status'),
        ),
    ]
