# Generated by Django 4.1.6 on 2023-10-04 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0043_merge_20230928_2354'),
        ('food', '0044_openinghour_is_close'),
    ]

    operations = [
    ]
