# Generated by Django 4.1.6 on 2023-10-04 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0045_merge_20231004_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='local_url',
            field=models.ImageField(blank=True, null=True, upload_to='images/%Y/%m/%d/', verbose_name='Local URL'),
        ),
    ]
