# Generated by Django 4.1.6 on 2023-10-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0047_alter_category_menu'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_menu_imported',
            field=models.BooleanField(default=False, verbose_name='otter menu imported successfully'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_menu_importing',
            field=models.BooleanField(default=False, verbose_name='otter menu importing'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='is_store_close',
            field=models.BooleanField(default=False, verbose_name='otter store closed'),
        ),
    ]
