# Generated by Django 4.1.6 on 2023-10-14 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0048_restaurant_is_menu_imported_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='timezone',
            field=models.CharField(default='+00:00', max_length=10),
        ),
    ]
