# Generated by Django 4.1.6 on 2023-10-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0050_alter_restaurant_timezone'),
    ]

    operations = [
        migrations.CreateModel(
            name='POS_DATA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('pos_type', models.CharField(choices=[('Clover', 'Clover'), ('Toast', 'Toast')], max_length=50, verbose_name='pos company')),
                ('external_id', models.CharField(max_length=100, verbose_name='external data id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='category',
            name='pos_identifier',
            field=models.ManyToManyField(blank=True, to='food.pos_data', verbose_name='pos data'),
        ),
        migrations.AddField(
            model_name='menu',
            name='pos_identifier',
            field=models.ManyToManyField(blank=True, to='food.pos_data', verbose_name='pos data'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='pos_identifier',
            field=models.ManyToManyField(blank=True, to='food.pos_data', verbose_name='pos data'),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='pos_identifier',
            field=models.ManyToManyField(blank=True, to='food.pos_data', verbose_name='pos data'),
        ),
    ]
