# Generated by Django 4.1.6 on 2023-10-26 21:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0051_pos_data_category_pos_identifier_menu_pos_identifier_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='category',
            name='show_in_overview',
            field=models.BooleanField(default=True, verbose_name='Show in overview'),
        ),
    ]
