# Generated by Django 4.1.6 on 2023-10-27 04:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0052_category_image_category_show_in_overview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetable',
            name='opening_hour',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opening_hour', to='food.openinghour', verbose_name='Opening_hour'),
        ),
    ]
