# Generated by Django 4.1.6 on 2023-11-14 12:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0056_alter_menuitem_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiergroup',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers', to='food.menu', verbose_name='Menu'),
        ),
    ]
