# Generated by Django 4.1.6 on 2024-01-05 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0058_alter_category_menu_alter_menuitem_menu_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_menu_imported',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='is_menu_importing',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='otter_auth_token',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='otter_client_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='otter_client_secret',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='otter_x_event_id',
        ),
        migrations.RemoveField(
            model_name='restaurant',
            name='otter_x_store_id',
        ),
        migrations.AddField(
            model_name='location',
            name='is_menu_imported',
            field=models.BooleanField(default=False, verbose_name='otter menu imported successfully'),
        ),
        migrations.AddField(
            model_name='location',
            name='is_menu_importing',
            field=models.BooleanField(default=False, verbose_name='otter menu importing'),
        ),
        migrations.AddField(
            model_name='location',
            name='otter_x_event_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='otter event id'),
        ),
        migrations.AddField(
            model_name='location',
            name='otter_x_store_id',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='otter store id'),
        ),
    ]
