# Generated by Django 4.1.6 on 2024-01-05 17:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0059_remove_restaurant_is_menu_imported_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiergroup',
            name='menu',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='food.menu', verbose_name='Menu'),
        ),
    ]
