# Generated by Django 4.1.6 on 2024-01-09 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0060_alter_modifiergroup_menu'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menu',
            options={'ordering': ['showing', '-id'], 'verbose_name': 'Menu', 'verbose_name_plural': 'Menus'},
        ),
        migrations.AddField(
            model_name='menu',
            name='showing',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
