# Generated by Django 4.1.6 on 2024-02-26 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0062_alter_restaurant_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='is_location_closed',
            field=models.BooleanField(default=False, verbose_name='location closed'),
        ),
    ]
