# Generated by Django 4.1.6 on 2024-03-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0063_location_is_location_closed'),
    ]

    operations = [
        migrations.CreateModel(
            name='SpecialHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('opens_at', models.TimeField(blank=True, null=True, verbose_name='Opens at')),
                ('closes_at', models.TimeField(blank=True, null=True, verbose_name='Closes at')),
                ('is_closed', models.BooleanField(blank=True, default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='menu',
            name='special_hours',
            field=models.ManyToManyField(blank=True, to='food.specialhour', verbose_name='Special Hours'),
        ),
    ]
