# Generated by Django 4.1.6 on 2024-03-19 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0064_specialhour_menu_special_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='inflation_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='inflation percent'),
        ),
    ]
