# Generated by Django 4.1.6 on 2024-03-20 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0065_restaurant_inflation_percent'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='reward_point_equivalent',
            field=models.FloatField(default=1, verbose_name='Reward point equivalent'),
        ),
    ]
