# Generated by Django 4.1.6 on 2024-03-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0066_restaurant_reward_point_equivalent'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='is menu item disabled'),
        ),
    ]
