# Generated by Django 4.1.6 on 2024-04-01 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0068_category_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='disabled'),
        ),
        migrations.AddField(
            model_name='menu',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='disabled'),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='disabled'),
        ),
    ]
