# Generated by Django 4.1.6 on 2024-04-01 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0069_category_disabled_menu_disabled_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='shared_menu', to='food.menu', verbose_name='shared with'),
        ),
    ]
