# Generated by Django 4.1.6 on 2024-04-03 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0070_alter_category_shared_with'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='shared_with',
            field=models.ManyToManyField(blank=True, related_name='categories_list', to='food.menu', verbose_name='shared with'),
        ),
    ]
