# Generated by Django 4.1.6 on 2024-04-17 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0071_alter_category_shared_with'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='bag_price',
            field=models.FloatField(default=0, verbose_name='bag price'),
        ),
    ]
