# Generated by Django 4.1.6 on 2024-04-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0072_restaurant_bag_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_available_today',
            field=models.BooleanField(default=True, verbose_name='Is Available Today'),
        ),
    ]
