# Generated by Django 4.1.6 on 2024-04-25 23:27

import django.contrib.postgres.fields
from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0072_restaurant_bag_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='order_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('delivery', 'DELIVERY'), ('restaurant_delivery', 'RESTAURANT_DELIVERY'), ('pickup', 'PICKUP'), ('dine_in', 'DINE_IN')], max_length=30, verbose_name='Order types'), blank=True, default=food.models.get_order_method_default, size=None),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='payment_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('stripe', 'STRIPE'), ('card', 'CARD'), ('paypal', 'PAYPAL'), ('cash', 'CASH')], max_length=30, verbose_name='Payment methods'), blank=True, default=food.models.get_payment_method_default, size=None),
        ),
    ]
