# Generated by Django 4.1.6 on 2024-04-25 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0073_menuitem_is_available_today'),
        ('food', '0073_restaurant_order_methods_restaurant_payment_methods'),
    ]

    operations = [
    ]
