# Generated by Django 4.1.6 on 2024-04-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0074_merge_20240425_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='utensil_price',
            field=models.FloatField(default=0, verbose_name='utensil price'),
        ),
    ]
