# Generated by Django 4.1.6 on 2024-05-09 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_appstore_version'),
        ('food', '0075_restaurant_utensil_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address', verbose_name='Address'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address', verbose_name='Address'),
        ),
    ]
