# Generated by Django 4.1.6 on 2024-05-08 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0075_restaurant_utensil_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='use_bag_price_on_delivery',
            field=models.BooleanField(default=False, verbose_name='add bag price on delivery'),
        ),
    ]
