# Generated by Django 4.1.6 on 2024-05-09 21:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0076_location_address_restaurant_address'),
        ('food', '0076_restaurant_use_bag_price_on_delivery'),
    ]

    operations = [
    ]
