# Generated by Django 4.1.6 on 2024-05-14 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0077_merge_20240509_1437'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='banner_image',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='banner_image',
            field=models.ManyToManyField(blank=True, related_name='banner_of_restaurant', to='food.image', verbose_name='Banner'),
        ),
    ]
