# Generated by Django 4.1.6 on 2024-05-16 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0078_remove_restaurant_banner_image_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantOMSUsagesTracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('modified_date', models.DateTimeField(auto_now=True)),
                ('oms_version', models.CharField(max_length=30, verbose_name='oms version')),
                ('last_updated', models.DateTimeField(auto_now=True, verbose_name='last updated')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.location', verbose_name='location')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.restaurant', verbose_name='restaurant')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
