# Generated by Django 4.1.6 on 2024-05-20 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0079_restaurantomsusagestracker'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='showing',
            field=models.PositiveIntegerField(default=1, verbose_name='sorting'),
        ),
    ]
