# Generated by Django 4.1.6 on 2024-05-20 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0080_location_showing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='location',
            options={'ordering': ['showing', '-id'], 'verbose_name': 'Location', 'verbose_name_plural': 'Locations'},
        ),
    ]
