# Generated by Django 4.1.6 on 2024-05-23 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0081_alter_location_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='is_alcoholic',
            field=models.BooleanField(default=False, verbose_name='Is alcoholic'),
        ),
    ]
