# Generated by Django 4.1.6 on 2024-05-24 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0082_menuitem_is_alcoholic'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='stripe_fee',
            field=models.BooleanField(default=False, verbose_name='Stripe fee'),
        ),
    ]
