# Generated by Django 4.1.6 on 2024-05-31 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0084_category_showing'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['showing', 'id'], 'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
    ]
