# Generated by Django 4.1.6 on 2024-06-08 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0085_alter_category_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='inflation_percent',
            field=models.PositiveIntegerField(default=0, verbose_name='inflation percent'),
        ),
    ]
