# Generated by Django 4.1.6 on 2024-06-08 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0086_menu_inflation_percent'),
        ('food', '0086_menu_modifiers_show_reverse'),
    ]

    operations = [
    ]
