# Generated by Django 4.1.6 on 2024-06-20 06:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0087_merge_20240608_0121'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifierGroupOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.menuitem')),
                ('modifier_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.modifiergroup')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('menu_item', 'modifier_group')},
            },
        ),
    ]
