# Generated by Django 4.1.6 on 2024-06-28 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_address_address_line_address_business_name_and_more'),
        ('food', '0088_modifiergrouporder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.address', verbose_name='Address'),
        ),
    ]
