# Generated by Django 4.1.6 on 2024-07-02 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0089_alter_restaurant_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='modifiergroup',
            name='is_available',
            field=models.BooleanField(default=True, verbose_name='Is Available'),
        ),
        migrations.AddField(
            model_name='modifiergroup',
            name='is_available_today',
            field=models.BooleanField(default=True, verbose_name='Is Available Today'),
        ),
    ]
