# Generated by Django 4.1.6 on 2024-07-02 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0090_modifiergroup_is_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='menuitem',
            options={'ordering': ['showing', '-id'], 'verbose_name': 'Menu Item', 'verbose_name_plural': 'Menu Items'},
        ),
        migrations.AddField(
            model_name='menuitem',
            name='showing',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
