# Generated by Django 4.1.6 on 2024-07-05 03:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0091_alter_uberauthmodel_token'),
        ('food', '0091_alter_menuitem_options_menuitem_showing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='payment_details',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.paymentdetails', verbose_name='Payment Details'),
        ),
    ]
