# Generated by Django 4.1.6 on 2024-07-18 08:28

import django.contrib.postgres.fields
from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0092_alter_restaurant_payment_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='payment_methods_pickup',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('stripe', 'STRIPE'), ('card', 'CARD'), ('paypal', 'PAYPAL'), ('cash', 'CASH')], max_length=30, verbose_name='Payment methods'), blank=True, default=food.models.get_payment_method_default, size=None),
        ),
    ]
