# Generated by Django 4.1.6 on 2024-08-01 04:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0093_restaurant_payment_methods_pickup'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModifiersItemsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.menuitem')),
                ('modifier_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='food.modifiergroup')),
            ],
            options={
                'ordering': ['order'],
                'unique_together': {('menu_item', 'modifier_item')},
            },
        ),
    ]
