# Generated by Django 4.1.6 on 2024-08-01 04:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0094_modifiersitemsorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modifiersitemsorder',
            name='modifier_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modifiers_item_list', to='food.modifiergroup'),
        ),
    ]
