# Generated by Django 4.1.6 on 2024-08-06 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0095_alter_modifiersitemsorder_modifier_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='third_party_do',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='location',
            name='use_third_party_do',
            field=models.BooleanField(default=False),
        ),
    ]
