# Generated by Django 4.1.6 on 2024-08-06 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0096_location_third_party_do_location_use_third_party_do'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='rating',
            field=models.IntegerField(default=0, verbose_name='ratings'),
        ),
    ]
