# Generated by Django 4.1.6 on 2024-09-09 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0098_location_latitude_location_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='receive_call_for_order',
            field=models.BooleanField(default=False),
        ),
    ]
