# Generated by Django 4.1.6 on 2024-09-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0099_restaurant_receive_call_for_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='service_fee',
            field=models.FloatField(default=0.99),
        ),
    ]
