# Generated by Django 4.1.6 on 2024-09-29 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0100_restaurant_service_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='use_delivery_inflation',
            field=models.BooleanField(default=False),
        ),
    ]
