# Generated by Django 4.1.6 on 2024-10-07 04:12

import django.contrib.postgres.fields
from django.db import migrations, models
import food.models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0101_restaurant_use_delivery_inflation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='payment_methods',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('stripe', 'STRIPE'), ('card', 'CARD'), ('paypal', 'PAYPAL'), ('cash', 'CASH'), ('wallet', 'WALLET')], max_length=30, verbose_name='Payment methods'), blank=True, default=food.models.get_payment_method_default, size=None),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='payment_methods_pickup',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('stripe', 'STRIPE'), ('card', 'CARD'), ('paypal', 'PAYPAL'), ('cash', 'CASH'), ('wallet', 'WALLET')], max_length=30, verbose_name='Payment methods'), blank=True, default=food.models.get_payment_method_default, size=None),
        ),
    ]
