# Generated by Django 4.1.6 on 2024-10-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0102_alter_restaurant_payment_methods_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accept_scheduled_order',
            field=models.BooleanField(default=True),
        ),
    ]
