# Generated by Django 4.1.6 on 2024-10-29 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0103_restaurant_accept_scheduled_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='latitude',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='longitude',
            field=models.FloatField(default=0),
        ),
    ]
