# Generated by Django 4.1.6 on 2024-11-16 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0104_restaurant_latitude_restaurant_longitude'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='logo',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logo_of_restaurant', to='food.image', verbose_name='Logo'),
        ),
    ]
