# Generated by Django 4.1.6 on 2024-11-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0105_restaurant_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='logo',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='logos/%Y/%m/%d/', verbose_name='Logo'),
        ),
    ]
