# Generated by Django 4.1.6 on 2024-11-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0106_alter_restaurant_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='delivery_fee',
            field=models.FloatField(default=0, verbose_name='default delivery fee'),
        ),
    ]
