# Generated by Django 4.1.6 on 2024-11-24 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0107_restaurant_delivery_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='allow_group_order',
            field=models.BooleanField(default=False),
        ),
    ]
