# Generated by Django 4.1.6 on 2024-12-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0108_menuitem_allow_group_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_remote_Kitchen',
            field=models.BooleanField(default=False, verbose_name='is remote kitchen'),
        ),
    ]
