# Generated by Django 4.1.6 on 2024-12-10 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0109_restaurant_is_remote_kitchen'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_chatchef_bd',
            field=models.BooleanField(default=False, verbose_name='is chatchef bd'),
        ),
    ]
