# Generated by Django 4.1.6 on 2024-12-19 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0113_forrkuseraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ForRKUserAddress',
        ),
    ]
