# Generated by Django 4.1.6 on 2024-12-23 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0114_delete_forrkuseraddress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_chatchef_bd',
        ),
    ]
