# Generated by Django 4.1.6 on 2024-12-23 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0115_remove_restaurant_is_chatchef_bd'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='is_chatchef_bd',
            field=models.BooleanField(default=False, verbose_name='is chatchef bd'),
        ),
    ]
