# Generated by Django 4.1.6 on 2024-12-23 08:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0116_restaurant_is_chatchef_bd'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='is_chatchef_bd',
        ),
    ]
