# Generated by Django 4.1.6 on 2025-01-19 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0118_restaurant_is_chatchef_bd'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='accept_first_second_third_user_reward',
            field=models.BooleanField(default=False, help_text='Allow the creation of first, second, and third order rewards for users.', verbose_name='Accept First, Second, and Third User Rewards'),
        ),
    ]
