# Generated by Django 4.1.6 on 2025-02-05 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0119_restaurant_accept_first_second_third_user_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_banner',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='restaurant_banners/%Y/%m/%d/', verbose_name='Restaurant_banner'),
        ),
    ]
