# Generated by Django 4.1.6 on 2025-02-11 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0119_restaurant_accept_first_second_third_user_reward'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='payment_account',
            field=models.CharField(choices=[('chatchef', 'ChatChef'), ('techchef', 'TechChef')], default='chatchef', help_text='Select the payment account to use for this restaurant.', max_length=50),
        ),
    ]
