# Generated by Django 4.1.6 on 2025-02-05 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0121_restaurant_average_rating'),
    ]

    operations = [
        migrations.CreateModel(
            name='RemoteKitchenCuisine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Cuisine Name')),
                ('icon', models.ImageField(blank=True, null=True, upload_to='cuisine_icons/%Y/%m/%d/', verbose_name='Cuisine Icon')),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuisines', to='food.restaurant')),
            ],
        ),
    ]
