# Generated by Django 4.1.6 on 2025-02-11 05:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0122_remotekitchencuisine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remotekitchencuisine',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(related_name='restaurants', to='food.remotekitchencuisine'),
        ),
    ]
