# Generated by Django 4.1.6 on 2025-02-11 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0123_remove_remotekitchencuisine_restaurant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='food.remotekitchencuisine'),
        ),
    ]
