# Generated by Django 4.1.6 on 2025-02-11 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0124_alter_restaurant_cuisines'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='Restaurant', to='food.remotekitchencuisine'),
        ),
    ]
