# Generated by Django 4.1.6 on 2025-02-11 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0125_alter_restaurant_cuisines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='cuisines',
        ),
    ]
