# Generated by Django 4.1.6 on 2025-02-11 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0126_remove_restaurant_cuisines'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cuisines',
            field=models.ManyToManyField(blank=True, related_name='restaurants', to='food.remotekitchencuisine'),
        ),
    ]
