# Generated by Django 4.1.6 on 2025-02-11 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0120_restaurant_payment_account'),
        ('food', '0127_restaurant_cuisines'),
    ]

    operations = [
    ]
