# Generated by Django 4.2.19 on 2025-03-24 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0129_restaurant_voucher_restriction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='voucher_restriction',
            field=models.BooleanField(default=True, help_text='Restrict the use of vouchers with other vouchers to this restaurant.', verbose_name='Voucher Restriction'),
        ),
    ]
