# Generated by Django 4.2.19 on 2025-04-23 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0130_alter_restaurant_voucher_restriction'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='discount_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Percentage discount applied to all menu items of this restaurant', max_digits=5, verbose_name='restaurant discount percentage'),
        ),
    ]
