# Generated by Django 4.2.19 on 2025-04-27 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0131_restaurant_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='store_type',
            field=models.CharField(choices=[('restaurant', 'Restaurant'), ('salons', 'Salons'), ('hotels', 'Hotels'), ('medicine', 'Medicine')], default='restaurant', help_text='Select the type of store.', max_length=50, verbose_name='Store Type'),
        ),
    ]
