# Generated by Django 4.2.19 on 2025-04-23 10:44

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0131_restaurant_discount_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), help_text='Base price after applying the restaurant discount', max_digits=10, verbose_name='Discounted Price'),
        ),
    ]
