# Generated by Django 4.2.19 on 2025-04-25 15:38

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0132_menuitem_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='original_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=Decimal('0.00'), help_text='Initial price of the item before any discount', max_digits=10, null=True, verbose_name='Original Prices'),
        ),
    ]
