# Generated by Django 4.2.19 on 2025-04-27 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0132_restaurant_store_type'),
        ('food', '0133_menuitem_original_price'),
    ]

    operations = [
    ]
