# Generated by Django 4.2.19 on 2025-04-27 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0134_merge_20250427_0201'),
        ('food', '0134_merge_20250427_0204'),
    ]

    operations = [
    ]
