# Generated by Django 4.2.19 on 2025-04-28 08:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0135_merge_20250427_0425'),
        ('food', '0135_merge_20250427_0720'),
    ]

    operations = [
    ]
