# Generated by Django 4.2.19 on 2025-05-25 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0136_merge_20250428_0153'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='auto_accept_orders',
            field=models.BooleanField(default=False, verbose_name='Auto Accept Orders'),
        ),
    ]
