# Generated by Django 4.2.19 on 2025-05-26 06:16

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0137_add_trigram_indexes"),
        ("food", "0137_restaurant_auto_accept_orders"),
    ]

    operations = []
