# Generated by Django 4.2.19 on 2025-06-02 11:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0138_merge_20250526_1216"),
        ("food", "0139_alter_menuitem_discounted_price"),
    ]

    operations = []
