# Generated by Django 4.2.19 on 2025-06-01 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0139_alter_menuitem_discounted_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='boosted_average_ticket_size',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Boosted average ticket size'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='boosted_monthly_sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Boosted monthly sales count'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='boosted_total_gross_revenue',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12, verbose_name='Boosted total gross revenue'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='boosted_total_sales_count',
            field=models.PositiveIntegerField(default=0, verbose_name='Boosted total sales count'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Priority 1'), (2, 'Priority 2')], default=2, verbose_name='Restaurant Boost Priority'),
        ),
    ]
