# Generated by Django 4.2.19 on 2025-06-01 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0140_restaurant_boosted_average_ticket_size_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='priority',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Priority 1'), (2, 'Priority 2')], default=1, verbose_name='Restaurant Boost Priority'),
        ),
    ]
