# Generated by Django 4.2.19 on 2025-06-02 11:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0140_merge_20250602_1712"),
    ]

    operations = [
        migrations.AddField(
            model_name="menuitem",
            name="available_end_time",
            field=models.TimeField(
                blank=True,
                help_text="Time when the item is no longer available",
                null=True,
                verbose_name="Available End Time",
            ),
        ),
        migrations.AddField(
            model_name="menuitem",
            name="available_start_time",
            field=models.TimeField(
                blank=True,
                help_text="Time when the item becomes available",
                null=True,
                verbose_name="Available Start Time",
            ),
        ),
    ]
