# Generated by Django 4.2.19 on 2025-06-18 08:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0141_alter_restaurant_priority"),
        ("food", "0141_menuitem_available_end_time_and_more"),
    ]

    operations = []
