# Generated by Django 4.2.19 on 2025-06-22 20:15

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("food", "0142_merge_20250618_0312"),
        ("food", "0142_merge_20250618_1440"),
    ]

    operations = []
