# Generated by Django 4.1.6 on 2024-01-19 20:12

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0061_alter_menu_options_menu_showing'),
        ('QR_Code', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='location',
            field=models.OneToOneField(default=33, on_delete=django.db.models.deletion.CASCADE, to='food.location', verbose_name='restaurant'),
            preserve_default=False,
        ),
    ]
