# Generated by Django 4.1.6 on 2024-07-08 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QR_Code', '0003_alter_qrcode_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcode',
            name='business_card_qrlink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='business_card_qrlink'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='business_card_qrlink_scanned',
            field=models.IntegerField(default=0, verbose_name='business_card_qrlink_scanned'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='coupon_qrlink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='flyer_qrlink'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='coupon_qrlink_scanned',
            field=models.IntegerField(default=0, verbose_name='coupon_qrlink_scanned'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='flyer_qrlink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='flyer_qrlink'),
        ),
        migrations.AddField(
            model_name='qrcode',
            name='flyer_qrlink_scanned',
            field=models.IntegerField(default=0, verbose_name='flyer_qrlink_scanned'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='banner_qrlink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='banner_qrlink'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='banner_qrlink_scanned',
            field=models.IntegerField(default=0, verbose_name='table_qrlink_scanned'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='poster_qrlink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='poster_qrlink'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='poster_qrlink_scanned',
            field=models.IntegerField(default=0, verbose_name='table_qrlink_scanned'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='social_qrlink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='social_qrlink'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='social_qrlink_scanned',
            field=models.IntegerField(default=0, verbose_name='table_qrlink_scanned'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='table_qrlink',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='table_qr'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='table_qrlink_scanned',
            field=models.IntegerField(default=0, verbose_name='table_qrlink_scanned'),
        ),
    ]
