name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy the app
        uses: appleboy/ssh-action@master
        with:
          host:  ${{ secrets.DIGITALOCEAN_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_PRIVATE_KEY }}
          port: ${{ secrets.DIGITALOCEAN_PORT }}
          script: |
            cd ~/chatchef_dir/chatchef-backend
            git stash
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            sudo service gunicorn_chatchef restart
