name: Deploy to DigitalOcean Prod

on:
  push:
    branches:
      - main  # ✅ Trigger only when pushing to the production branch

jobs:
  deploy:
    name: Deploy Prod to Live Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PROD_SSH_HOST }}              # ✅ New: production IP/domain
          username: ${{ secrets.PROD_SSH_USER }}           # ✅ New: production SSH username
          port: ${{ secrets.PROD_SSH_PORT }}               # ✅ New: production SSH port (usually 22)
          key: ${{ secrets.PROD_SSH_PRIVATE_KEY }}         # ✅ New: production private key
          script: |
            cd ~/hungrytiger-backend-new                   # ✅ Correct production directory
            git stash
            git pull origin main
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn                # ✅ Adjust this if your prod uses a different service name
