name: Deploy to DigitalOcean Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy dev branch to test env
        uses: appleboy/ssh-action@master
        with:
          host:  ${{ secrets.DIGITALOCEAN_TEST_HOST }}
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}
          key: ${{ secrets.DIGITALOCEAN_TEST_PRIVATE_KEY }}
          port: ${{ secrets.DIGITALOCEAN_PORT }}
          script: |
            cd ~/chatchef_dir
            git stash
            git pull
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            sudo service gunicorn_chatchef restart
