name: Deploy to DigitalOcean Dev

on:
  push:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy Dev to Test Server
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: SSH & Deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}              # ✅ Corrected name
          username: ${{ secrets.SSH_USER }}          # ✅ Corrected name
          port: ${{ secrets.SSH_PORT }}              # ✅ Corrected name
          key: ${{ secrets.SSH_PRIVATE_KEY }}        # ✅ Corrected name
          script: |
            cd ~/chatchef_dir
            git stash
            git pull origin dev
            source venv/bin/activate
            pip install -r requirements.txt
            python manage.py migrate
            python manage.py collectstatic --noinput
            sudo systemctl restart gunicorn_chatchef
