name: Deploy to DigitalOcean Dev

on:
  push:
    branches:
      - dev  # Trigger deployment only on dev branch push

jobs:
  deploy:
    name: Deploy Dev to Test Server
    runs-on: ubuntu-latest

    steps:
      - name: Deploy dev branch to test environment
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.DIGITALOCEAN_TEST_HOST }}            # e.g., 167.172.76.xxx
          username: ${{ secrets.DIGITALOCEAN_USERNAME }}         # e.g., hungrytiger
          key: ${{ secrets.DIGITALOCEAN_TEST_PRIVATE_KEY }}      # Your local private key
          port: ${{ secrets.DIGITALOCEAN_PORT }}                 # Usually 22

          script: |
            echo "➡️ Deploying to test server..."
            cd ~/chatchef_dir                                     # Your project directory
            git stash                                             # Stash any local changes
            git pull origin dev                                   # Pull latest changes from dev branch
            source venv/bin/activate                              # Activate virtualenv
            pip install -r requirements.txt                       # Install dependencies
            python manage.py migrate                              # Run DB migrations
            python manage.py collectstatic --noinput              # Optional: collect static files
            sudo systemctl restart gunicorn_chatchef              # Restart Gunicorn service
            echo "✅ Deployment complete."
